const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { createAgentMemory } = require('../backend/ai/agent-memory');

(async () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'game-vault-agent-memory-'));
  const memory = createAgentMemory({ root, now: () => '2026-09-14T13:30:00.000Z', limit: 3 });
  await memory.append('demo', 'v1', { role: 'user', content: 'اولین پیام' });
  await memory.append('demo', 'v1', { role: 'assistant', content: 'اولین پاسخ' });
  const userMessage = await memory.append('demo', 'v1', { role: 'user', content: 'پیام دوم' });
  await memory.append('demo', 'v1', { role: 'assistant', content: 'پاسخ دوم' });
  const conversation = await memory.read('demo', 'v1');
  assert.deepEqual(conversation.map(item => item.content), ['اولین پاسخ', 'پیام دوم', 'پاسخ دوم'], 'memory must retain the latest messages in order');
  assert.equal(conversation[0].createdAt, '2026-09-14T13:30:00.000Z');
  assert.ok(conversation.every(item => item.id), 'persisted messages must have stable identifiers for UI actions');
  const branched = await memory.editAndTrim('demo', 'v1', userMessage.at(-1).id, 'پیام دوم ویرایش‌شده');
  assert.deepEqual(branched.map(item => item.content), ['اولین پاسخ', 'پیام دوم ویرایش‌شده'], 'editing a user message must remove later stale replies');
  await memory.append('demo', 'v1', { role: 'assistant', content: 'پاسخ جایگزین' });
  const assistant = (await memory.read('demo', 'v1')).at(-1);
  await memory.remove('demo', 'v1', assistant.id);
  assert.deepEqual((await memory.read('demo', 'v1')).map(item => item.content), ['اولین پاسخ', 'پیام دوم ویرایش‌شده'], 'removing one message must preserve the rest of the conversation');
  assert.deepEqual(await memory.read('other', 'v1'), [], 'each game/version must have isolated memory');

  const first = await memory.createSession('sessions', 'v1');
  await memory.append('sessions', 'v1', { role: 'user', content: 'گفتگوی قدیمی', attachment: { name: 'notes.md', type: 'text/markdown', size: 42 } }, first.id);
  const second = await memory.createSession('sessions', 'v1');
  await memory.append('sessions', 'v1', { role: 'user', content: 'گفتگوی جدید' }, second.id);
  await memory.updateSession('sessions', 'v1', first.id, { title: 'یادداشت‌های پروژه', pinned: true });
  await memory.updateSession('sessions', 'v1', second.id, { archived: true });
  const sessions = await memory.listSessions('sessions', 'v1');
  assert.deepEqual(sessions.map(session => session.id), [first.id], 'archived sessions must be hidden and pinned sessions must stay first');
  assert.equal(sessions[0].title, 'یادداشت‌های پروژه', 'a renamed session must keep its explicit title');
  const uploaded = await memory.read('sessions', 'v1', first.id);
  assert.deepEqual(uploaded[0].attachment, { name: 'notes.md', type: 'text/markdown', size: 42 }, 'attachment metadata must persist without the file payload');
  await memory.clear('demo', 'v1');
  assert.deepEqual(await memory.read('demo', 'v1'), [], 'clearing a conversation must not affect other conversations');
  fs.rmSync(root, { recursive: true, force: true });
  console.log('agent memory passed');
})().catch(error => { console.error(error); process.exitCode = 1; });
