let buildGame='';let buildVersion='';let buildPoll=null;
const build$=selector=>document.querySelector(selector);
const selectedTargets=()=>[...document.querySelectorAll('#buildSheet input:checked')].map(input=>input.value);
function setBuildLog(text){build$('#buildLog').textContent=text;}
function closeBuildSheet(){build$('#buildSheet').classList.add('hidden');clearInterval(buildPoll);buildPoll=null;}
async function refreshBuildTools(){const targets=selectedTargets();if(!targets.length){build$('#buildTools').innerHTML='';setBuildLog('حداقل یک خروجی انتخاب کن.');return []}const data=await api('/api/build-tools?targets='+encodeURIComponent(targets.join(',')));build$('#buildTools').innerHTML=data.tools.map(tool=>'<div class="build-tool"><div><b>'+tool.label+'</b><small>'+tool.sizeLabel+' · برای '+tool.requiredFor.join(', ')+'</small></div>'+(tool.installed?'<span class="tool-ok">✓ آماده</span>':'<button data-install-tool="'+tool.id+'">نصب پس از تأیید</button>')+'</div>').join('');document.querySelectorAll('[data-install-tool]').forEach(button=>button.onclick=async()=>{const tool=button.dataset.installTool;if(!confirm('ابزار انتخاب‌شده نصب شود؟ حجم تقریبی در کارت نمایش داده شده است.'))return;button.disabled=true;setBuildLog('در حال نصب ابزار…');try{const result=await api('/api/build-tools/install',{method:'POST',body:JSON.stringify({toolId:tool,confirmed:true})});setBuildLog(result.result.output||'نصب تمام شد.');await refreshBuildTools()}catch(error){setBuildLog(error.message);button.disabled=false}});return data.tools;}
function openBuildSheet(gameId,version){buildGame=gameId;buildVersion=version||'v1.0.0';build$('#buildTitle').textContent='ساخت خروجی · '+gameId+' · '+buildVersion;build$('#buildSheet').classList.remove('hidden');setBuildLog('در حال بررسی ابزارهای نصب…');refreshBuildTools().catch(error=>setBuildLog(error.message));}
async function refreshBuildJob(id){try{const data=await api('/api/builds/'+encodeURIComponent(id));const job=data.job;const text=[...job.logs.map(item=>item.line),job.error].filter(Boolean).join('\n');setBuildLog(text||'در حال آماده‌سازی…');if(job.status==='completed'||job.status==='failed'){clearInterval(buildPoll);buildPoll=null;if(job.status==='completed')renderArtifacts(job.artifacts)}}catch(error){setBuildLog(error.message);clearInterval(buildPoll);buildPoll=null}}
function renderArtifacts(artifacts){const links=artifacts.map(item=>'<a class="artifact" href="'+item.url+'">↓ '+item.platform+' · '+item.format+'</a>').join('');build$('#buildLog').innerHTML='ساخت با موفقیت انجام شد.<br>'+links;}
async function startBuild(){const targets=selectedTargets();if(!targets.length)return setBuildLog('حداقل یک خروجی را انتخاب کن.');const tools=await refreshBuildTools();if(tools.some(tool=>!tool.installed))return setBuildLog('ابتدا ابزارهای ضروری را نصب کن. نصب فقط با تأیید تو انجام می‌شود.');const data=await api('/api/builds',{method:'POST',body:JSON.stringify({game:buildGame,version:buildVersion,targets})});setBuildLog('Job ساخت در صف قرار گرفت…');clearInterval(buildPoll);buildPoll=setInterval(()=>refreshBuildJob(data.job.id),1500);refreshBuildJob(data.job.id);}
async function showDownloads(){const data=await api('/api/builds?game='+encodeURIComponent(buildGame)+'&version='+encodeURIComponent(buildVersion));const artifacts=data.jobs.filter(job=>job.status==='completed').flatMap(job=>job.artifacts||[]);if(!artifacts.length)return setBuildLog('هنوز خروجی آماده‌ای برای این نسخه وجود ندارد.');renderArtifacts(artifacts);}
function attachBuildButtons(){document.querySelectorAll('.manage-card').forEach(card=>{if(card.querySelector('[data-build-game]'))return;const edit=card.querySelector('[data-edit]');if(!edit)return;const button=document.createElement('button');button.dataset.buildGame=edit.dataset.edit;button.textContent='خروجی نصب';button.onclick=()=>{const game=(typeof games!=='undefined'?games:[]).find(item=>item.id===button.dataset.buildGame);openBuildSheet(button.dataset.buildGame,game?.version)};card.querySelector('.manage-actions').append(button);});}
document.addEventListener('DOMContentLoaded',()=>{build$('#closeBuildSheet').onclick=closeBuildSheet;build$('#buildSheet').onclick=event=>{if(event.target===build$('#buildSheet'))closeBuildSheet()};document.querySelectorAll('#buildSheet input').forEach(input=>input.onchange=()=>refreshBuildTools().catch(error=>setBuildLog(error.message)));build$('#buildStart').onclick=()=>startBuild().catch(error=>setBuildLog(error.message));build$('#buildDownloads').onclick=()=>showDownloads().catch(error=>setBuildLog(error.message));setInterval(attachBuildButtons,600);});
