(() => {
  const api = async (path, options = {}) => { const response = await fetch(path, { headers: { 'content-type': 'application/json', ...(options.headers || {}) }, ...options }); const data = await response.json().catch(() => ({})); if (!response.ok) throw Error(data.error || 'خطا'); return data; };
  const esc = value => String(value ?? '').replace(/[&<>]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[char]));
  const render = async game => {
    const root = document.querySelector('#gameDetail'); if (!root) return;
    const panel = document.createElement('section'); panel.className = 'community-panel'; panel.innerHTML = '<div class="community-head"><div><span>جامعهٔ بازی</span><h2>امتیازها و دیدگاه‌ها</h2></div><b class="community-score">در حال بارگذاری…</b></div><div class="rate-row"><span>امتیاز شما:</span><div class="rate-stars">'+[1,2,3,4,5].map(value => '<button data-rate="'+value+'" aria-label="امتیاز '+value+'">☆</button>').join('')+'</div></div><form class="comment-form"><textarea required minlength="2" maxlength="1200" placeholder="نظر خودت را دربارهٔ این بازی بنویس…"></textarea><button>ارسال نظر</button><small></small></form><div class="comment-list"></div>';
    root.append(panel);
    const paint = async () => { const data = await api('/api/community?game=' + encodeURIComponent(game.id)); panel.querySelector('.community-score').textContent = data.rating.count ? '★ ' + data.rating.average.toLocaleString('fa-IR') + ' / ' + data.rating.count.toLocaleString('fa-IR') + ' رأی' : 'هنوز رأی ندارد'; panel.querySelector('.comment-list').innerHTML = data.comments.length ? data.comments.map(comment => '<article class="comment"><span class="comment-avatar">'+esc(String(comment.author||'?').trim().slice(0,1).toUpperCase()||'?')+'</span><div class="comment-body"><div class="comment-head"><b>'+esc(comment.author)+'</b><time>'+new Date(comment.at).toLocaleString('fa-IR')+'</time></div><p>'+esc(comment.text)+'</p>'+(comment.replies||[]).map(reply => '<div class="reply"><b>'+esc(reply.author)+'</b><p>'+esc(reply.text)+'</p></div>').join('')+'</div></article>').join('') : '<p class="comment-empty">اولین نظر این بازی را تو بنویس.</p>'; };
    panel.querySelectorAll('[data-rate]').forEach(button => button.onclick = async () => { try { await api('/api/community/rating', { method: 'POST', body: JSON.stringify({ game: game.id, value: Number(button.dataset.rate) }) }); panel.querySelectorAll('[data-rate]').forEach(item => item.textContent = Number(item.dataset.rate) <= Number(button.dataset.rate) ? '★' : '☆'); await paint(); } catch (error) { panel.querySelector('.comment-form small').textContent = error.message; } });
    panel.querySelector('.comment-form').onsubmit = async event => { event.preventDefault(); const text = panel.querySelector('textarea').value; try { await api('/api/community/comment', { method: 'POST', body: JSON.stringify({ game: game.id, text }) }); panel.querySelector('textarea').value = ''; await paint(); } catch (error) { panel.querySelector('.comment-form small').textContent = error.message; } };
    await paint();
  };
  document.addEventListener('game-detail-rendered', event => render(event.detail).catch(() => {}));
})();
