let games=[];const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function mountFreeStudio(){const nav=document.querySelector('.admin-nav nav');if(!nav||$('#openFreeStudio'))return;const button=document.createElement('button');button.id='openFreeStudio';button.className='nav-item';button.textContent='⌘ استادیو آزاد';button.onclick=openFreeStudio;nav.appendChild(button)}
async function openFreeStudio(){try{const data=await api('/api/theia/free',{method:'POST'});location.href=data.url}catch(error){alert(error.message)}}
async function api(p,o={}){const r=await fetch(p,{headers:{'content-type':'application/json',...(o.headers||{})},...o}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'خطا');return d}
async function init(){const session=await api('/api/session');if(!session.authenticated){location.href='/';return}if(session.user){document.querySelector('.admin-user b').textContent=session.user.name;document.querySelector('.admin-user small').textContent=session.user.role==='admin'?'Administrator':'User';document.querySelector('.admin-avatar').textContent=session.user.avatar||session.user.name[0];const name=document.querySelector('#adminProfileName'),avatar=document.querySelector('#adminProfileAvatar');if(name)name.textContent=session.user.name;if(avatar)avatar.textContent=session.user.avatar||session.user.name[0]}games=(await api('/api/games')).games;renderDashboard();renderCards()}
function renderDashboard(){const rating=games.length?games.reduce((s,g)=>s+Number(g.rating||0),0)/games.length:0;$('#adminGames').textContent=games.length.toLocaleString('fa-IR');$('#adminVersions').textContent=games.reduce((s,g)=>s+Number(g.versionCount||1),0).toLocaleString('fa-IR');$('#adminRating').textContent=rating.toFixed(1).replace(/\d/g,d=>'۰۱۲۳۴۵۶۷۸۹'[d]);$('#profileGames').textContent=games.length.toLocaleString('fa-IR');loadRealActivity();$('#releaseFlow').innerHTML=games.slice(0,5).map(g=>'<div class="release-item"><span class="release-icon">◈</span><span><b>'+esc(g.name)+'</b><small>نسخه '+esc(g.version||'v1.0.0')+' · '+((g.status||'published')==='published'?'منتشر شد':'در حال ساخت')+'</small></span></div>').join('')||'<small>پروژه‌ای موجود نیست</small>'}
async function loadRealActivity(){try{const data=await api('/api/activity/weekly'),days=Array.isArray(data.days)?data.days:[],values=days.map(day=>Number(day.play||0)+Number(day.download||0)),max=Math.max(1,...values);$('#neonChart').innerHTML=values.map((value,index)=>'<i title="'+esc(days[index].label+': '+value+' فعالیت')+'" style="height:'+Math.max(5,Math.round(value/max*100))+'%" data-value="'+value+'"></i>').join('')||'<small>فعالیتی ثبت نشده است</small>'}catch{$('#neonChart').innerHTML='<small>دریافت فعالیت ممکن نشد</small>'}}
function renderCards(){$('#manageCards').innerHTML=games.map(g=>'<article class="manage-card"><div class="manage-cover" style="background-image:url(\''+esc(g.image)+'\')"></div><div class="manage-content"><h3>'+esc(g.name)+'</h3><p>'+esc(g.description)+'</p><div class="manage-meta"><span>★ '+esc(g.rating)+'</span><span>'+esc(g.version||'v1.0.0')+'</span></div><div class="manage-actions"><button data-edit="'+esc(g.id)+'">ویرایش در Studio</button><button class="delete" data-delete="'+esc(g.id)+'">حذف بازی</button></div><div class="project-actions"><button data-vscode="'+esc(g.id)+'" data-version="'+esc(g.version||'v1.0.0')+'" title="باز کردن پوشه در VS Code"><span data-icon="vscode"></span> باز کردن در VS Code</button><button data-copy-path="'+esc(g.id)+'" data-version="'+esc(g.version||'v1.0.0')+'" title="کپی مسیر پروژه"><span data-icon="copy"></span></button><button data-project-info="'+esc(g.id)+'" data-version="'+esc(g.version||'v1.0.0')+'" title="Git، حجم فایل و منابع"><span data-icon="chart"></span></button></div></div></article>').join('');document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>location.href='/theia.html?game='+encodeURIComponent(b.dataset.edit)+'&version='+encodeURIComponent((games.find(g=>g.id===b.dataset.edit)||{}).version||'v1.0.0'));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteGame(b.dataset.delete));window.GameVaultTools?.bind(document.querySelector('#manageCards'))}
async function deleteGame(id){if(!confirm('پوشه‌ی این بازی و همه نسخه‌های آن حذف شود؟'))return;await api('/api/game',{method:'DELETE',body:JSON.stringify({game:id})});games=games.filter(g=>g.id!==id);renderDashboard();renderCards()}
function openGameWizard(){const form=$('#gameWizardForm');if(!form)return;form.reset();$('#gameSlug').value='';$('#wizardMessage').textContent='';$('#gameWizard').classList.remove('hidden');document.body.classList.add('wizard-open');setTimeout(()=>$('#gameName')?.focus(),0)}function closeGameWizard(){const wizard=$('#gameWizard');if(!wizard)return;wizard.classList.add('hidden');document.body.classList.remove('wizard-open')}
$('#gameName').oninput=e=>{$('#gameSlug').value=e.target.value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')};
async function addGame(){const form=$('#gameWizardForm'),data=Object.fromEntries(new FormData(form));const image=$('#gameImage').files[0],packages=[...$('#gamePackage').files];if(image)data.image=image.name;data.rating=Number(data.rating||5);try{$('#wizardMessage').textContent='در حال ساخت پروژه...';const created=await api('/api/game',{method:'POST',body:JSON.stringify(data)});if(image){const raw=await readFile(image);await api('/api/upload',{method:'POST',body:JSON.stringify({game:created.game.slug,version:'v1.0.0',file:{name:image.name,base64:raw}})})}for(const file of packages){const raw=await readFile(file);const payload=file.name.toLowerCase().endsWith('.zip')?{game:created.game.slug,version:'v1.0.0',zipBase64:raw}:{game:created.game.slug,version:'v1.0.0',file:{name:file.name,base64:raw}};await api('/api/upload',{method:'POST',body:JSON.stringify(payload)})}games=(await api('/api/games')).games;renderDashboard();renderCards();closeGameWizard();new BroadcastChannel('game-vault').postMessage('game-created')}catch(error){$('#wizardMessage').textContent=error.message}}
function readFile(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file)})}
mountFreeStudio();document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{if(b.id==='openFreeStudio'){openFreeStudio();return}if(b.dataset.view==='profileView'){location.href='/profile.html';return}document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.admin-view').forEach(v=>v.classList.toggle('hidden',v.id!==b.dataset.view));$('#adminTitle').textContent=b.textContent.trim()});$('#logout').onclick=async()=>{await api('/api/auth/logout',{method:'POST'});location.href='/'};$('#addGame').onclick=openGameWizard;$('#closeGameWizard').onclick=closeGameWizard;$('#cancelGameWizard').onclick=closeGameWizard;$('#gameWizard').onclick=e=>{if(e.target.id==='gameWizard')closeGameWizard()};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#gameWizard').classList.contains('hidden'))closeGameWizard()});$('#gameWizardForm').onsubmit=e=>{e.preventDefault();addGame()};init();
setInterval(init,5000);
const gameVaultChannel=new BroadcastChannel('game-vault');gameVaultChannel.onmessage=()=>init();
