// ============================================================================
// FlowForge – Node Catalog (shared between client & server, pure data)
// کاتالوگ نودها: تعریف همه‌ی نودهای داخلی، یکپارچه‌سازی‌ها و نودهای سفارشی
// ============================================================================

export type ParamType =
  | "string"
  | "number"
  | "boolean"
  | "select"
  | "json"
  | "code"
  | "textarea";

export type ParamDef = {
  name: string;
  label: string;
  type: ParamType;
  default?: unknown;
  options?: { value: string; label: string }[];
  placeholder?: string;
  description?: string;
};

export type NodeDef = {
  type: string;
  name: string;
  category: string;
  icon: string;
  color: string;
  description: string;
  inputs: number; // 0 برای تریگرها
  outputs: string[]; // نام هندل‌های خروجی
  params: ParamDef[];
  trigger?: boolean;
  credentialType?: string;
  handler: string; // نام هندلر اجرایی در سمت سرور
  meta?: Record<string, unknown>;
};

// ---------------------------------------------------------------------------
// دسته‌بندی‌ها
// ---------------------------------------------------------------------------
export const CATEGORIES = [
  { id: "trigger", label: "تریگرها", icon: "⚡" },
  { id: "core", label: "هسته و منطق", icon: "🧩" },
  { id: "data", label: "پردازش داده", icon: "🧮" },
  { id: "code", label: "کدنویسی", icon: "💻" },
  { id: "ai", label: "هوش مصنوعی", icon: "🤖" },
  { id: "messaging", label: "پیام‌رسان‌ها", icon: "💬" },
  { id: "email", label: "ایمیل", icon: "✉️" },
  { id: "productivity", label: "بهره‌وری و پروژه", icon: "📋" },
  { id: "google", label: "Google Workspace", icon: "🟢" },
  { id: "microsoft", label: "Microsoft 365", icon: "🟦" },
  { id: "crm", label: "CRM و فروش", icon: "🤝" },
  { id: "marketing", label: "مارکتینگ", icon: "📣" },
  { id: "database", label: "دیتابیس‌ها", icon: "🗄️" },
  { id: "vector", label: "Vector DB / RAG", icon: "🧠" },
  { id: "storage", label: "ذخیره‌سازی فایل", icon: "📁" },
  { id: "devops", label: "توسعه و DevOps", icon: "🛠️" },
  { id: "ecommerce", label: "تجارت الکترونیک", icon: "🛒" },
  { id: "http", label: "HTTP و API", icon: "🌐" },
  { id: "iot", label: "IoT و شبکه", icon: "📡" },
  { id: "files", label: "فایل و تبدیل", icon: "📄" },
  { id: "analytics", label: "آنالیتیکس", icon: "📊" },
  { id: "social", label: "شبکه‌های اجتماعی", icon: "📱" },
  { id: "finance", label: "مالی و پرداخت", icon: "💳" },
  { id: "support", label: "پشتیبانی مشتری", icon: "🎧" },
  { id: "hr", label: "منابع انسانی", icon: "👥" },
  { id: "misc", label: "سایر", icon: "🔧" },
] as const;

const P = (
  name: string,
  label: string,
  type: ParamType,
  extra: Partial<ParamDef> = {},
): ParamDef => ({ name, label, type, ...extra });

const methodOptions = ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"].map(
  (m) => ({ value: m, label: m }),
);

// ---------------------------------------------------------------------------
// نودهای هسته‌ای (Core) – همه به‌صورت واقعی اجرا می‌شوند
// ---------------------------------------------------------------------------
const CORE_NODES: NodeDef[] = [
  // ------------------------------- Triggers -------------------------------
  {
    type: "manualTrigger",
    name: "Manual Trigger",
    category: "trigger",
    icon: "▶️",
    color: "#10b981",
    description: "شروع دستی جریان از داخل ویرایشگر",
    inputs: 0,
    outputs: ["main"],
    trigger: true,
    handler: "trigger",
    params: [P("payload", "داده اولیه (JSON)", "json", { default: "{}" })],
  },
  {
    type: "webhookTrigger",
    name: "Webhook",
    category: "trigger",
    icon: "🪝",
    color: "#f59e0b",
    description: "شروع جریان با درخواست HTTP روی مسیر /api/webhook/<path>",
    inputs: 0,
    outputs: ["main"],
    trigger: true,
    handler: "trigger",
    params: [
      P("path", "مسیر", "string", { default: "my-hook", placeholder: "my-hook" }),
      P("method", "متد", "select", { default: "POST", options: methodOptions }),
      P("respondMode", "پاسخ", "select", {
        default: "lastNode",
        options: [
          { value: "immediately", label: "فوری (202)" },
          { value: "lastNode", label: "خروجی آخرین نود" },
          { value: "respondNode", label: "با نود Respond to Webhook" },
        ],
      }),
      P("authToken", "توکن احراز هویت (اختیاری)", "string"),
    ],
  },
  {
    type: "scheduleTrigger",
    name: "Schedule",
    category: "trigger",
    icon: "⏰",
    color: "#8b5cf6",
    description: "اجرای زمان‌بندی‌شده با عبارت Cron",
    inputs: 0,
    outputs: ["main"],
    trigger: true,
    handler: "trigger",
    params: [
      P("cron", "عبارت Cron", "string", { default: "*/5 * * * *", description: "دقیقه ساعت روز ماه روزهفته" }),
      P("timezone", "منطقه زمانی", "string", { default: "Asia/Tehran" }),
    ],
  },
  {
    type: "pollingTrigger",
    name: "Polling Trigger",
    category: "trigger",
    icon: "🔄",
    color: "#8b5cf6",
    description: "بررسی دوره‌ای یک URL و شروع جریان در صورت تغییر داده",
    inputs: 0,
    outputs: ["main"],
    trigger: true,
    handler: "trigger",
    params: [
      P("url", "آدرس", "string", { placeholder: "https://api.example.com/items" }),
      P("intervalMinutes", "بازه (دقیقه)", "number", { default: 5 }),
      P("dedupeField", "فیلد یکتا", "string", { default: "id" }),
    ],
  },
  {
    type: "fileTrigger",
    name: "File System Watcher",
    category: "trigger",
    icon: "👁️",
    color: "#8b5cf6",
    description: "شروع جریان با ایجاد/تغییر/حذف فایل در پوشه",
    inputs: 0,
    outputs: ["main"],
    trigger: true,
    handler: "trigger",
    params: [
      P("path", "مسیر پوشه", "string", { default: "/files/inbox" }),
      P("events", "رویدادها", "select", {
        default: "all",
        options: [
          { value: "all", label: "همه" },
          { value: "add", label: "ایجاد" },
          { value: "change", label: "تغییر" },
          { value: "unlink", label: "حذف" },
        ],
      }),
      P("pattern", "الگوی فایل", "string", { default: "*" }),
    ],
  },
  {
    type: "emailTrigger",
    name: "Email Trigger (IMAP)",
    category: "trigger",
    icon: "📥",
    color: "#8b5cf6",
    description: "شروع جریان با دریافت ایمیل جدید",
    inputs: 0,
    outputs: ["main"],
    trigger: true,
    credentialType: "imap",
    handler: "trigger",
    params: [
      P("mailbox", "صندوق", "string", { default: "INBOX" }),
      P("onlyUnread", "فقط خوانده‌نشده", "boolean", { default: true }),
    ],
  },
  {
    type: "dbTrigger",
    name: "Database Trigger (CDC)",
    category: "trigger",
    icon: "🛎️",
    color: "#8b5cf6",
    description: "شروع جریان با INSERT/UPDATE/DELETE در جدول (LISTEN/NOTIFY یا Polling)",
    inputs: 0,
    outputs: ["main"],
    trigger: true,
    credentialType: "postgres",
    handler: "trigger",
    params: [
      P("table", "جدول", "string", { placeholder: "orders" }),
      P("events", "رویداد", "select", {
        default: "insert",
        options: [
          { value: "insert", label: "INSERT" },
          { value: "update", label: "UPDATE" },
          { value: "delete", label: "DELETE" },
          { value: "all", label: "همه" },
        ],
      }),
      P("mode", "حالت", "select", {
        default: "listen",
        options: [
          { value: "listen", label: "LISTEN/NOTIFY" },
          { value: "poll", label: "Polling" },
        ],
      }),
    ],
  },
  {
    type: "errorTrigger",
    name: "Error Trigger",
    category: "trigger",
    icon: "🚨",
    color: "#ef4444",
    description: "اجرا هنگام خطا در جریان‌های دیگر (Error Workflow)",
    inputs: 0,
    outputs: ["main"],
    trigger: true,
    handler: "trigger",
    params: [],
  },
  {
    type: "chatTrigger",
    name: "Chat Trigger",
    category: "trigger",
    icon: "💭",
    color: "#10b981",
    description: "شروع جریان با پیام چت (برای AI Agent)",
    inputs: 0,
    outputs: ["main"],
    trigger: true,
    handler: "trigger",
    params: [P("message", "پیام آزمایشی", "string", { default: "سلام" })],
  },

  // -------------------------------- Core ----------------------------------
  {
    type: "httpRequest",
    name: "HTTP Request",
    category: "http",
    icon: "🌐",
    color: "#0ea5e9",
    description: "ارسال درخواست HTTP با هر متد، هدر و بدنه",
    inputs: 1,
    outputs: ["main"],
    handler: "httpRequest",
    credentialType: "httpAuth",
    params: [
      P("method", "متد", "select", { default: "GET", options: methodOptions }),
      P("url", "آدرس", "string", { placeholder: "https://api.example.com/data" }),
      P("headers", "هدرها (JSON)", "json", { default: "{}" }),
      P("query", "Query Params (JSON)", "json", { default: "{}" }),
      P("bodyType", "نوع بدنه", "select", {
        default: "json",
        options: [
          { value: "json", label: "JSON" },
          { value: "form", label: "Form URL-Encoded" },
          { value: "raw", label: "Raw / XML" },
          { value: "none", label: "بدون بدنه" },
        ],
      }),
      P("body", "بدنه", "json", { default: "{}" }),
      P("responseFormat", "فرمت پاسخ", "select", {
        default: "auto",
        options: [
          { value: "auto", label: "خودکار" },
          { value: "json", label: "JSON" },
          { value: "text", label: "متن" },
        ],
      }),
      P("timeout", "Timeout (ms)", "number", { default: 30000 }),
      P("curl", "Import cURL (اختیاری)", "textarea", { placeholder: "curl -X POST https://..." }),
    ],
  },
  {
    type: "graphql",
    name: "GraphQL",
    category: "http",
    icon: "◈",
    color: "#e535ab",
    description: "اجرای Query/Mutation در GraphQL",
    inputs: 1,
    outputs: ["main"],
    handler: "graphql",
    credentialType: "httpAuth",
    params: [
      P("endpoint", "Endpoint", "string"),
      P("query", "Query", "code", { default: "query { __typename }" }),
      P("variables", "Variables (JSON)", "json", { default: "{}" }),
      P("headers", "هدرها (JSON)", "json", { default: "{}" }),
    ],
  },
  {
    type: "respondToWebhook",
    name: "Respond to Webhook",
    category: "http",
    icon: "↩️",
    color: "#0ea5e9",
    description: "ارسال پاسخ سفارشی به درخواست Webhook",
    inputs: 1,
    outputs: ["main"],
    handler: "respond",
    params: [
      P("statusCode", "کد وضعیت", "number", { default: 200 }),
      P("body", "بدنه (JSON یا عبارت)", "json", { default: "={{ $json }}" }),
    ],
  },
  {
    type: "set",
    name: "Edit Fields (Set)",
    category: "data",
    icon: "✏️",
    color: "#6366f1",
    description: "تنظیم یا تغییر فیلدهای هر آیتم",
    inputs: 1,
    outputs: ["main"],
    handler: "set",
    params: [
      P("fields", "فیلدها (JSON)", "json", { default: '{\n  "message": "={{ $json.name }}"\n}' }),
      P("keepOnlySet", "فقط فیلدهای تنظیم‌شده", "boolean", { default: false }),
    ],
  },
  {
    type: "if",
    name: "If",
    category: "core",
    icon: "🔀",
    color: "#22c55e",
    description: "شاخه‌بندی true/false بر اساس شرط",
    inputs: 1,
    outputs: ["true", "false"],
    handler: "if",
    params: [
      P("condition", "شرط (عبارت JS)", "string", { default: "={{ $json.value > 10 }}" }),
    ],
  },
  {
    type: "switch",
    name: "Switch",
    category: "core",
    icon: "🔃",
    color: "#22c55e",
    description: "مسیریابی چند‌شاخه بر اساس مقدار",
    inputs: 1,
    outputs: ["0", "1", "2", "3", "fallback"],
    handler: "switch",
    params: [
      P("value", "مقدار", "string", { default: "={{ $json.type }}" }),
      P("rules", "قوانین (آرایه JSON از مقادیر)", "json", { default: '["a", "b", "c", "d"]' }),
    ],
  },
  {
    type: "filter",
    name: "Filter",
    category: "data",
    icon: "🧹",
    color: "#6366f1",
    description: "نگه‌داشتن آیتم‌هایی که شرط را برآورده می‌کنند",
    inputs: 1,
    outputs: ["main"],
    handler: "filter",
    params: [P("condition", "شرط", "string", { default: "={{ $json.active === true }}" })],
  },
  {
    type: "merge",
    name: "Merge",
    category: "data",
    icon: "🔗",
    color: "#6366f1",
    description: "ادغام چند جریان داده",
    inputs: 2,
    outputs: ["main"],
    handler: "merge",
    params: [
      P("mode", "حالت", "select", {
        default: "append",
        options: [
          { value: "append", label: "Append" },
          { value: "combineByPosition", label: "Combine by position" },
          { value: "combineByKey", label: "Combine by key" },
          { value: "waitAll", label: "Wait for all" },
        ],
      }),
      P("key", "کلید (برای combineByKey)", "string", { default: "id" }),
    ],
  },
  {
    type: "loop",
    name: "Loop Over Items (Split in Batches)",
    category: "core",
    icon: "🔁",
    color: "#f97316",
    description: "پردازش دسته‌ای؛ خروجی loop برای هر دسته و done پس از اتمام",
    inputs: 1,
    outputs: ["loop", "done"],
    handler: "loop",
    params: [P("batchSize", "اندازه دسته", "number", { default: 1 })],
  },
  {
    type: "wait",
    name: "Wait",
    category: "core",
    icon: "⏳",
    color: "#f97316",
    description: "توقف برای مدت مشخص",
    inputs: 1,
    outputs: ["main"],
    handler: "wait",
    params: [P("seconds", "ثانیه", "number", { default: 1 })],
  },
  {
    type: "noOp",
    name: "No Operation",
    category: "core",
    icon: "⚪",
    color: "#94a3b8",
    description: "عبور بدون تغییر",
    inputs: 1,
    outputs: ["main"],
    handler: "noop",
    params: [],
  },
  {
    type: "stopAndError",
    name: "Stop and Error",
    category: "core",
    icon: "🛑",
    color: "#ef4444",
    description: "توقف جریان با خطا",
    inputs: 1,
    outputs: [],
    handler: "stopAndError",
    params: [P("message", "پیام خطا", "string", { default: "Stopped by workflow" })],
  },
  {
    type: "executeWorkflow",
    name: "Execute Sub-Workflow",
    category: "core",
    icon: "🧬",
    color: "#a855f7",
    description: "فراخوانی یک جریان دیگر و دریافت خروجی آن",
    inputs: 1,
    outputs: ["main"],
    handler: "executeWorkflow",
    params: [
      P("workflowId", "شناسه Workflow", "number"),
      P("waitForCompletion", "انتظار برای اتمام", "boolean", { default: true }),
    ],
  },
  {
    type: "humanApproval",
    name: "Human in the Loop (Approval)",
    category: "core",
    icon: "🙋",
    color: "#eab308",
    description: "نیاز به تأیید انسانی قبل از ادامه",
    inputs: 1,
    outputs: ["approved", "rejected"],
    handler: "humanApproval",
    params: [
      P("message", "پیام تأیید", "string", { default: "آیا این اقدام تأیید می‌شود؟" }),
      P("autoDecision", "تصمیم در اجرای دستی", "select", {
        default: "approved",
        options: [
          { value: "approved", label: "تأیید" },
          { value: "rejected", label: "رد" },
        ],
      }),
      P("notifyChannel", "کانال اطلاع‌رسانی", "select", {
        default: "none",
        options: [
          { value: "none", label: "هیچ" },
          { value: "telegram", label: "Telegram" },
          { value: "bale", label: "Bale" },
          { value: "email", label: "Email" },
        ],
      }),
    ],
  },
  {
    type: "globalVariables",
    name: "Global Variables",
    category: "core",
    icon: "🌍",
    color: "#94a3b8",
    description: "خواندن همه متغیرهای سراسری",
    inputs: 1,
    outputs: ["main"],
    handler: "globalVariables",
    params: [],
  },

  // -------------------------------- Code ----------------------------------
  {
    type: "code",
    name: "Code (JavaScript)",
    category: "code",
    icon: "💻",
    color: "#f59e0b",
    description: "اجرای جاوااسکریپت با دسترسی به $input، $json، $vars، fetch و require",
    inputs: 1,
    outputs: ["main"],
    handler: "codeJs",
    params: [
      P("mode", "حالت", "select", {
        default: "allItems",
        options: [
          { value: "allItems", label: "یک‌بار برای همه آیتم‌ها" },
          { value: "eachItem", label: "برای هر آیتم" },
        ],
      }),
      P("code", "کد", "code", {
        default:
          "// خروجی باید آرایه‌ای از آیتم‌ها باشد\nconst items = $input.all();\nreturn items.map((item, i) => ({ json: { ...item.json, index: i } }));",
      }),
      P("npmPackages", "پکیج‌های npm (با کاما)", "string", { placeholder: "lodash, dayjs" }),
    ],
  },
  {
    type: "pythonCode",
    name: "Code (Python)",
    category: "code",
    icon: "🐍",
    color: "#3b82f6",
    description: "اجرای پایتون (python3 روی هاست/کانتینر)",
    inputs: 1,
    outputs: ["main"],
    handler: "codePython",
    params: [
      P("code", "کد", "code", {
        default: "import json, sys\nitems = json.load(sys.stdin)\nprint(json.dumps([{'json': {**i['json'], 'py': True}} for i in items]))",
      }),
    ],
  },
  {
    type: "bash",
    name: "Bash Script Executor",
    category: "code",
    icon: "🖥️",
    color: "#111827",
    description: "اجرای اسکریپت Bash و بازگرداندن stdout/stderr/exitCode",
    inputs: 1,
    outputs: ["main"],
    handler: "bash",
    params: [
      P("script", "اسکریپت", "code", { default: "echo \"Hello from FlowForge\"\ndate" }),
      P("cwd", "پوشه اجرا", "string", { default: "/tmp" }),
      P("timeout", "Timeout (ms)", "number", { default: 30000 }),
    ],
  },
  {
    type: "expression",
    name: "Expression Evaluator",
    category: "code",
    icon: "🧾",
    color: "#f59e0b",
    description: "ارزیابی عبارت JS و قرار دادن نتیجه در فیلد",
    inputs: 1,
    outputs: ["main"],
    handler: "expression",
    params: [
      P("expression", "عبارت", "string", { default: "={{ $json.a + $json.b }}" }),
      P("outputField", "فیلد خروجی", "string", { default: "result" }),
    ],
  },

  // -------------------------------- Data ----------------------------------
  {
    type: "sort",
    name: "Sort",
    category: "data",
    icon: "↕️",
    color: "#6366f1",
    description: "مرتب‌سازی آیتم‌ها",
    inputs: 1,
    outputs: ["main"],
    handler: "sort",
    params: [
      P("field", "فیلد", "string", { default: "id" }),
      P("order", "ترتیب", "select", {
        default: "asc",
        options: [
          { value: "asc", label: "صعودی" },
          { value: "desc", label: "نزولی" },
        ],
      }),
    ],
  },
  {
    type: "limit",
    name: "Limit",
    category: "data",
    icon: "✂️",
    color: "#6366f1",
    description: "محدود کردن تعداد آیتم‌ها",
    inputs: 1,
    outputs: ["main"],
    handler: "limit",
    params: [P("max", "حداکثر", "number", { default: 10 })],
  },
  {
    type: "removeDuplicates",
    name: "Remove Duplicates",
    category: "data",
    icon: "🧽",
    color: "#6366f1",
    description: "حذف آیتم‌های تکراری",
    inputs: 1,
    outputs: ["main"],
    handler: "removeDuplicates",
    params: [P("field", "فیلد مقایسه (خالی = کل آیتم)", "string")],
  },
  {
    type: "splitOut",
    name: "Split Out",
    category: "data",
    icon: "🪓",
    color: "#6366f1",
    description: "تبدیل یک آرایه داخل آیتم به چند آیتم",
    inputs: 1,
    outputs: ["main"],
    handler: "splitOut",
    params: [P("field", "فیلد آرایه", "string", { default: "items" })],
  },
  {
    type: "aggregate",
    name: "Aggregate",
    category: "data",
    icon: "🧺",
    color: "#6366f1",
    description: "تجمیع همه آیتم‌ها در یک آیتم",
    inputs: 1,
    outputs: ["main"],
    handler: "aggregate",
    params: [P("outputField", "فیلد خروجی", "string", { default: "data" })],
  },
  {
    type: "summarize",
    name: "Summarize",
    category: "data",
    icon: "Σ",
    color: "#6366f1",
    description: "محاسبه sum/avg/count/min/max روی فیلد",
    inputs: 1,
    outputs: ["main"],
    handler: "summarize",
    params: [
      P("field", "فیلد", "string", { default: "amount" }),
      P("groupBy", "گروه‌بندی بر اساس", "string"),
    ],
  },
  {
    type: "renameKeys",
    name: "Rename Keys",
    category: "data",
    icon: "🏷️",
    color: "#6366f1",
    description: "تغییر نام کلیدها",
    inputs: 1,
    outputs: ["main"],
    handler: "renameKeys",
    params: [P("mapping", "نگاشت (JSON: old→new)", "json", { default: '{"old_name": "newName"}' })],
  },
  {
    type: "dateTime",
    name: "Date & Time",
    category: "data",
    icon: "📅",
    color: "#6366f1",
    description: "عملیات تاریخ و زمان (شمسی/میلادی)",
    inputs: 1,
    outputs: ["main"],
    handler: "dateTime",
    params: [
      P("operation", "عملیات", "select", {
        default: "now",
        options: [
          { value: "now", label: "زمان فعلی" },
          { value: "format", label: "قالب‌بندی" },
          { value: "add", label: "افزودن" },
          { value: "jalali", label: "تبدیل به شمسی" },
        ],
      }),
      P("value", "مقدار", "string", { default: "={{ $json.date }}" }),
      P("amount", "مقدار افزودن (ثانیه)", "number", { default: 3600 }),
      P("outputField", "فیلد خروجی", "string", { default: "dateTime" }),
    ],
  },
  {
    type: "crypto",
    name: "Crypto",
    category: "data",
    icon: "🔐",
    color: "#6366f1",
    description: "Hash / HMAC / UUID / Base64",
    inputs: 1,
    outputs: ["main"],
    handler: "crypto",
    params: [
      P("action", "عملیات", "select", {
        default: "sha256",
        options: [
          { value: "md5", label: "MD5" },
          { value: "sha256", label: "SHA256" },
          { value: "hmac", label: "HMAC-SHA256" },
          { value: "uuid", label: "UUID" },
          { value: "base64", label: "Base64 encode" },
          { value: "base64decode", label: "Base64 decode" },
        ],
      }),
      P("value", "مقدار", "string", { default: "={{ $json.value }}" }),
      P("secret", "کلید (HMAC)", "string"),
      P("outputField", "فیلد خروجی", "string", { default: "hash" }),
    ],
  },
  {
    type: "markdown",
    name: "Markdown ⇄ HTML",
    category: "data",
    icon: "📝",
    color: "#6366f1",
    description: "تبدیل Markdown به HTML و برعکس",
    inputs: 1,
    outputs: ["main"],
    handler: "markdown",
    params: [
      P("value", "مقدار", "string", { default: "={{ $json.text }}" }),
      P("outputField", "فیلد خروجی", "string", { default: "html" }),
    ],
  },
  {
    type: "htmlExtract",
    name: "HTML Extract",
    category: "data",
    icon: "🧲",
    color: "#6366f1",
    description: "استخراج داده از HTML با Regex/تگ",
    inputs: 1,
    outputs: ["main"],
    handler: "htmlExtract",
    params: [
      P("html", "HTML", "string", { default: "={{ $json.body }}" }),
      P("regex", "الگو (Regex)", "string", { default: "<title>(.*?)</title>" }),
      P("outputField", "فیلد خروجی", "string", { default: "extracted" }),
    ],
  },
  {
    type: "xml",
    name: "XML ⇄ JSON",
    category: "data",
    icon: "🧾",
    color: "#6366f1",
    description: "تبدیل XML به JSON و برعکس",
    inputs: 1,
    outputs: ["main"],
    handler: "xml",
    params: [
      P("mode", "حالت", "select", {
        default: "toJson",
        options: [
          { value: "toJson", label: "XML → JSON" },
          { value: "toXml", label: "JSON → XML" },
        ],
      }),
      P("value", "مقدار", "string", { default: "={{ $json.xml }}" }),
    ],
  },
  {
    type: "compression",
    name: "Compression",
    category: "files",
    icon: "🗜️",
    color: "#0891b2",
    description: "فشرده‌سازی/استخراج gzip",
    inputs: 1,
    outputs: ["main"],
    handler: "compression",
    params: [
      P("mode", "حالت", "select", {
        default: "compress",
        options: [
          { value: "compress", label: "فشرده‌سازی (gzip)" },
          { value: "decompress", label: "استخراج" },
        ],
      }),
      P("value", "مقدار", "string", { default: "={{ JSON.stringify($json) }}" }),
    ],
  },
  {
    type: "convertToFile",
    name: "Convert to File",
    category: "files",
    icon: "📄",
    color: "#0891b2",
    description: "تبدیل آیتم‌ها به فایل CSV/JSON/TXT و ذخیره در /files",
    inputs: 1,
    outputs: ["main"],
    handler: "convertToFile",
    params: [
      P("format", "فرمت", "select", {
        default: "csv",
        options: [
          { value: "csv", label: "CSV" },
          { value: "json", label: "JSON" },
          { value: "txt", label: "TXT" },
          { value: "xlsx", label: "XLSX (CSV سازگار)" },
        ],
      }),
      P("fileName", "نام فایل", "string", { default: "export-{{ $now }}.csv" }),
    ],
  },
  {
    type: "readWriteFile",
    name: "Read/Write File",
    category: "files",
    icon: "💾",
    color: "#0891b2",
    description: "خواندن/نوشتن فایل روی دیسک لوکال",
    inputs: 1,
    outputs: ["main"],
    handler: "readWriteFile",
    params: [
      P("operation", "عملیات", "select", {
        default: "read",
        options: [
          { value: "read", label: "خواندن" },
          { value: "write", label: "نوشتن" },
          { value: "list", label: "لیست پوشه" },
          { value: "delete", label: "حذف" },
        ],
      }),
      P("path", "مسیر", "string", { default: "/files/example.txt" }),
      P("content", "محتوا (برای نوشتن)", "textarea", { default: "={{ JSON.stringify($json) }}" }),
    ],
  },
  {
    type: "extractFromFile",
    name: "Extract From File",
    category: "files",
    icon: "📤",
    color: "#0891b2",
    description: "استخراج داده از CSV/JSON/TXT",
    inputs: 1,
    outputs: ["main"],
    handler: "extractFromFile",
    params: [
      P("path", "مسیر فایل", "string", { default: "/files/data.csv" }),
      P("format", "فرمت", "select", {
        default: "csv",
        options: [
          { value: "csv", label: "CSV" },
          { value: "json", label: "JSON" },
          { value: "txt", label: "TXT" },
        ],
      }),
    ],
  },
  {
    type: "rss",
    name: "RSS Read",
    category: "http",
    icon: "📰",
    color: "#f97316",
    description: "خواندن فید RSS/Atom",
    inputs: 1,
    outputs: ["main"],
    handler: "rss",
    params: [P("url", "آدرس فید", "string", { placeholder: "https://example.com/feed.xml" })],
  },

  // --------------------------------- AI -----------------------------------
  {
    type: "aiAgent",
    name: "AI Agent",
    category: "ai",
    icon: "🤖",
    color: "#ec4899",
    description: "عامل هوشمند با حافظه، ابزارها (HTTP، Code، Sub-workflow) و هر LLM",
    inputs: 1,
    outputs: ["main"],
    handler: "aiAgent",
    credentialType: "llm",
    params: [
      P("provider", "ارائه‌دهنده", "select", {
        default: "openai",
        options: [
          { value: "openai", label: "OpenAI" },
          { value: "anthropic", label: "Anthropic" },
          { value: "google", label: "Google Gemini" },
          { value: "codex", label: "Codex (device-code auth)" },
          { value: "ollama", label: "Ollama (لوکال)" },
          { value: "openrouter", label: "OpenRouter" },
          { value: "custom", label: "OpenAI-compatible سفارشی" },
        ],
      }),
      P("model", "مدل", "string", { default: "gpt-4o-mini" }),
      P("systemPrompt", "System Prompt", "textarea", { default: "You are a helpful automation agent. Answer in the user's language." }),
      P("prompt", "پیام کاربر", "textarea", { default: "={{ $json.message }}" }),
      P("tools", "ابزارها (JSON)", "json", {
        default: '[\n  {"name":"http","description":"Call an HTTP URL","type":"http"},\n  {"name":"calculator","description":"Evaluate math","type":"js"}\n]',
      }),
      P("memoryKey", "کلید حافظه", "string", { default: "={{ $json.sessionId || 'default' }}" }),
      P("maxIterations", "حداکثر تکرار", "number", { default: 5 }),
      P("temperature", "Temperature", "number", { default: 0.3 }),
    ],
  },
  {
    type: "llmChat",
    name: "LLM Chat Model",
    category: "ai",
    icon: "🗣️",
    color: "#ec4899",
    description: "فراخوانی مستقیم مدل زبانی (OpenAI/Anthropic/Gemini/Codex/Ollama)",
    inputs: 1,
    outputs: ["main"],
    handler: "llmChat",
    credentialType: "llm",
    params: [
      P("provider", "ارائه‌دهنده", "select", {
        default: "openai",
        options: [
          { value: "openai", label: "OpenAI" },
          { value: "anthropic", label: "Anthropic" },
          { value: "google", label: "Google Gemini" },
          { value: "codex", label: "Codex" },
          { value: "ollama", label: "Ollama" },
          { value: "custom", label: "OpenAI-compatible" },
        ],
      }),
      P("model", "مدل", "string", { default: "gpt-4o-mini" }),
      P("systemPrompt", "System Prompt", "textarea", { default: "" }),
      P("prompt", "Prompt", "textarea", { default: "={{ $json.prompt }}" }),
      P("jsonOutput", "خروجی JSON", "boolean", { default: false }),
      P("temperature", "Temperature", "number", { default: 0.3 }),
    ],
  },
  {
    type: "codexAgent",
    name: "Codex Agent",
    category: "ai",
    icon: "🧑‍💻",
    color: "#111827",
    description: "اتصال به Codex از طریق اشتراک موجود (device-code auth) به‌عنوان Chat Model",
    inputs: 1,
    outputs: ["main"],
    handler: "llmChat",
    credentialType: "codex",
    params: [
      P("provider", "ارائه‌دهنده", "select", { default: "codex", options: [{ value: "codex", label: "Codex" }] }),
      P("model", "مدل", "string", { default: "codex-mini-latest" }),
      P("systemPrompt", "System Prompt", "textarea", { default: "You are Codex, an expert software engineer." }),
      P("prompt", "دستور", "textarea", { default: "={{ $json.task }}" }),
      P("temperature", "Temperature", "number", { default: 0.2 }),
    ],
  },
  {
    type: "embeddings",
    name: "Embeddings",
    category: "vector",
    icon: "🧬",
    color: "#ec4899",
    description: "تولید بردار Embedding برای متن",
    inputs: 1,
    outputs: ["main"],
    handler: "embeddings",
    credentialType: "llm",
    params: [
      P("provider", "ارائه‌دهنده", "select", {
        default: "local",
        options: [
          { value: "openai", label: "OpenAI" },
          { value: "ollama", label: "Ollama" },
          { value: "local", label: "لوکال (hash-based)" },
        ],
      }),
      P("model", "مدل", "string", { default: "text-embedding-3-small" }),
      P("text", "متن", "string", { default: "={{ $json.text }}" }),
    ],
  },
  {
    type: "textSplitter",
    name: "Text Splitter",
    category: "vector",
    icon: "✂️",
    color: "#ec4899",
    description: "تقسیم متن به Chunkها برای RAG",
    inputs: 1,
    outputs: ["main"],
    handler: "textSplitter",
    params: [
      P("text", "متن", "string", { default: "={{ $json.text }}" }),
      P("chunkSize", "اندازه Chunk", "number", { default: 500 }),
      P("overlap", "هم‌پوشانی", "number", { default: 50 }),
    ],
  },
  {
    type: "documentLoader",
    name: "Document Loader",
    category: "vector",
    icon: "📚",
    color: "#ec4899",
    description: "بارگذاری اسناد از فایل/URL برای ingestion",
    inputs: 1,
    outputs: ["main"],
    handler: "documentLoader",
    params: [
      P("source", "منبع", "select", {
        default: "file",
        options: [
          { value: "file", label: "فایل لوکال" },
          { value: "url", label: "URL" },
          { value: "field", label: "فیلد ورودی" },
        ],
      }),
      P("path", "مسیر / URL / فیلد", "string", { default: "/files/knowledge.txt" }),
    ],
  },
  {
    type: "vectorStore",
    name: "Vector Store",
    category: "vector",
    icon: "🧠",
    color: "#ec4899",
    description: "درج/جستجوی بردار در Pinecone، Weaviate، Milvus، Qdrant، pgvector یا حافظه لوکال",
    inputs: 1,
    outputs: ["main"],
    handler: "vectorStore",
    credentialType: "vectorDb",
    params: [
      P("provider", "ارائه‌دهنده", "select", {
        default: "local",
        options: [
          { value: "local", label: "Local (in-process)" },
          { value: "pgvector", label: "PostgreSQL pgvector" },
          { value: "pinecone", label: "Pinecone" },
          { value: "weaviate", label: "Weaviate" },
          { value: "milvus", label: "Milvus" },
          { value: "qdrant", label: "Qdrant" },
          { value: "chroma", label: "Chroma" },
        ],
      }),
      P("operation", "عملیات", "select", {
        default: "insert",
        options: [
          { value: "insert", label: "درج" },
          { value: "search", label: "جستجو" },
          { value: "clear", label: "پاک‌سازی" },
        ],
      }),
      P("collection", "Collection / Index", "string", { default: "knowledge" }),
      P("query", "متن جستجو", "string", { default: "={{ $json.question }}" }),
      P("topK", "Top K", "number", { default: 4 }),
    ],
  },
  {
    type: "ragChain",
    name: "RAG Q&A Chain",
    category: "vector",
    icon: "🔎",
    color: "#ec4899",
    description: "پایپ‌لاین کامل: retrieval از Vector Store + generation با LLM",
    inputs: 1,
    outputs: ["main"],
    handler: "ragChain",
    credentialType: "llm",
    params: [
      P("collection", "Collection", "string", { default: "knowledge" }),
      P("question", "سؤال", "string", { default: "={{ $json.question }}" }),
      P("provider", "LLM", "select", {
        default: "openai",
        options: [
          { value: "openai", label: "OpenAI" },
          { value: "ollama", label: "Ollama" },
          { value: "anthropic", label: "Anthropic" },
          { value: "codex", label: "Codex" },
        ],
      }),
      P("model", "مدل", "string", { default: "gpt-4o-mini" }),
      P("topK", "Top K", "number", { default: 4 }),
    ],
  },
  {
    type: "guardrails",
    name: "Guardrails",
    category: "ai",
    icon: "🛡️",
    color: "#ec4899",
    description: "اعمال قوانین: کلمات ممنوعه، PII، طول، JSON Schema",
    inputs: 1,
    outputs: ["pass", "blocked"],
    handler: "guardrails",
    params: [
      P("text", "متن", "string", { default: "={{ $json.output }}" }),
      P("blockedWords", "کلمات ممنوعه (با کاما)", "string", { default: "password, secret" }),
      P("maxLength", "حداکثر طول", "number", { default: 5000 }),
      P("blockPII", "مسدودسازی PII (ایمیل/شماره کارت)", "boolean", { default: true }),
    ],
  },
  {
    type: "sentiment",
    name: "Sentiment Analysis",
    category: "ai",
    icon: "🙂",
    color: "#ec4899",
    description: "تحلیل احساسات متن (lexicon + LLM اختیاری)",
    inputs: 1,
    outputs: ["main"],
    handler: "sentiment",
    params: [P("text", "متن", "string", { default: "={{ $json.text }}" })],
  },
  {
    type: "textClassifier",
    name: "Text Classifier",
    category: "ai",
    icon: "🏷️",
    color: "#ec4899",
    description: "دسته‌بندی متن با کلیدواژه یا LLM",
    inputs: 1,
    outputs: ["main"],
    handler: "textClassifier",
    params: [
      P("text", "متن", "string", { default: "={{ $json.text }}" }),
      P("categories", "دسته‌ها (JSON: name→keywords[])", "json", {
        default: '{"support":["مشکل","خطا","error"],"sales":["قیمت","خرید","price"]}',
      }),
    ],
  },
  {
    type: "aiMemory",
    name: "Agent Memory",
    category: "ai",
    icon: "🧠",
    color: "#ec4899",
    description: "خواندن/پاک کردن حافظه مکالمه Agent",
    inputs: 1,
    outputs: ["main"],
    handler: "aiMemory",
    params: [
      P("operation", "عملیات", "select", {
        default: "read",
        options: [
          { value: "read", label: "خواندن" },
          { value: "clear", label: "پاک کردن" },
        ],
      }),
      P("memoryKey", "کلید", "string", { default: "default" }),
    ],
  },

  // ------------------------------ Messaging -------------------------------
  {
    type: "bale",
    name: "Bale Messenger",
    category: "messaging",
    icon: "🟢",
    color: "#16a34a",
    description: "ارسال متن/تصویر/فایل در پیام‌رسان بله (tapi.bale.ai)",
    inputs: 1,
    outputs: ["main"],
    handler: "bale",
    credentialType: "bale",
    params: [
      P("operation", "عملیات", "select", {
        default: "sendMessage",
        options: [
          { value: "sendMessage", label: "ارسال متن" },
          { value: "sendPhoto", label: "ارسال تصویر" },
          { value: "sendDocument", label: "ارسال فایل" },
          { value: "getUpdates", label: "دریافت پیام‌ها" },
          { value: "setWebhook", label: "تنظیم Webhook" },
        ],
      }),
      P("chatId", "Chat ID", "string", { default: "={{ $json.chatId }}" }),
      P("text", "متن / Caption", "textarea", { default: "={{ $json.text }}" }),
      P("fileUrl", "آدرس فایل/تصویر", "string"),
    ],
  },
  {
    type: "baleTrigger",
    name: "Bale Trigger",
    category: "trigger",
    icon: "🟢",
    color: "#16a34a",
    description: "دریافت پیام از بله (Webhook)",
    inputs: 0,
    outputs: ["main"],
    trigger: true,
    credentialType: "bale",
    handler: "trigger",
    params: [P("path", "مسیر Webhook", "string", { default: "bale" })],
  },
  {
    type: "soroush",
    name: "Soroush Plus",
    category: "messaging",
    icon: "🔵",
    color: "#2563eb",
    description: "ارسال متن/تصویر/فایل در سروش پلاس (Bot API)",
    inputs: 1,
    outputs: ["main"],
    handler: "soroush",
    credentialType: "soroush",
    params: [
      P("operation", "عملیات", "select", {
        default: "sendMessage",
        options: [
          { value: "sendMessage", label: "ارسال متن" },
          { value: "sendFile", label: "ارسال فایل" },
          { value: "getUpdates", label: "دریافت پیام‌ها" },
        ],
      }),
      P("chatId", "Chat ID", "string", { default: "={{ $json.chatId }}" }),
      P("text", "متن", "textarea", { default: "={{ $json.text }}" }),
      P("fileUrl", "آدرس فایل", "string"),
    ],
  },
  {
    type: "soroushTrigger",
    name: "Soroush Trigger",
    category: "trigger",
    icon: "🔵",
    color: "#2563eb",
    description: "دریافت پیام از سروش (Webhook)",
    inputs: 0,
    outputs: ["main"],
    trigger: true,
    credentialType: "soroush",
    handler: "trigger",
    params: [P("path", "مسیر Webhook", "string", { default: "soroush" })],
  },
  {
    type: "telegram",
    name: "Telegram",
    category: "messaging",
    icon: "✈️",
    color: "#0284c7",
    description: "ارسال پیام/عکس/فایل با Telegram Bot API",
    inputs: 1,
    outputs: ["main"],
    handler: "telegram",
    credentialType: "telegram",
    params: [
      P("operation", "عملیات", "select", {
        default: "sendMessage",
        options: [
          { value: "sendMessage", label: "ارسال متن" },
          { value: "sendPhoto", label: "ارسال تصویر" },
          { value: "sendDocument", label: "ارسال فایل" },
          { value: "getUpdates", label: "دریافت پیام‌ها" },
        ],
      }),
      P("chatId", "Chat ID", "string", { default: "={{ $json.chatId }}" }),
      P("text", "متن", "textarea", { default: "={{ $json.text }}" }),
      P("fileUrl", "آدرس فایل", "string"),
      P("parseMode", "Parse Mode", "select", {
        default: "HTML",
        options: [
          { value: "HTML", label: "HTML" },
          { value: "Markdown", label: "Markdown" },
        ],
      }),
    ],
  },
  {
    type: "telegramTrigger",
    name: "Telegram Trigger",
    category: "trigger",
    icon: "✈️",
    color: "#0284c7",
    description: "دریافت پیام از تلگرام (Webhook)",
    inputs: 0,
    outputs: ["main"],
    trigger: true,
    credentialType: "telegram",
    handler: "trigger",
    params: [P("path", "مسیر Webhook", "string", { default: "telegram" })],
  },
  {
    type: "slack",
    name: "Slack",
    category: "messaging",
    icon: "💼",
    color: "#4a154b",
    description: "ارسال پیام به Slack (Webhook یا Bot Token)",
    inputs: 1,
    outputs: ["main"],
    handler: "slack",
    credentialType: "slack",
    params: [
      P("channel", "کانال", "string", { default: "#general" }),
      P("text", "متن", "textarea", { default: "={{ $json.text }}" }),
    ],
  },
  {
    type: "discord",
    name: "Discord",
    category: "messaging",
    icon: "🎮",
    color: "#5865f2",
    description: "ارسال پیام به Discord Webhook",
    inputs: 1,
    outputs: ["main"],
    handler: "discord",
    credentialType: "discord",
    params: [
      P("webhookUrl", "Webhook URL", "string"),
      P("content", "متن", "textarea", { default: "={{ $json.text }}" }),
    ],
  },
  {
    type: "sendEmail",
    name: "Send Email (SMTP)",
    category: "email",
    icon: "✉️",
    color: "#dc2626",
    description: "ارسال ایمیل با SMTP",
    inputs: 1,
    outputs: ["main"],
    handler: "sendEmail",
    credentialType: "smtp",
    params: [
      P("to", "گیرنده", "string", { default: "={{ $json.email }}" }),
      P("subject", "موضوع", "string", { default: "FlowForge Notification" }),
      P("html", "متن (HTML)", "textarea", { default: "<p>{{ $json.text }}</p>" }),
    ],
  },

  // ------------------------------ Database --------------------------------
  {
    type: "postgres",
    name: "PostgreSQL",
    category: "database",
    icon: "🐘",
    color: "#336791",
    description: "اجرای Query روی PostgreSQL",
    inputs: 1,
    outputs: ["main"],
    handler: "postgres",
    credentialType: "postgres",
    params: [
      P("operation", "عملیات", "select", {
        default: "query",
        options: [
          { value: "query", label: "Execute Query" },
          { value: "insert", label: "Insert" },
          { value: "select", label: "Select" },
        ],
      }),
      P("query", "SQL", "code", { default: "SELECT now() AS server_time" }),
      P("table", "جدول (برای insert/select)", "string"),
      P("params", "پارامترها (آرایه JSON)", "json", { default: "[]" }),
    ],
  },

  // -------------------------------- IoT -----------------------------------
  {
    type: "tcp",
    name: "TCP Socket",
    category: "iot",
    icon: "🔌",
    color: "#0f766e",
    description: "ارسال/دریافت داده روی سوکت TCP لوکال",
    inputs: 1,
    outputs: ["main"],
    handler: "tcp",
    params: [
      P("host", "Host", "string", { default: "127.0.0.1" }),
      P("port", "Port", "number", { default: 9000 }),
      P("data", "داده ارسالی", "string", { default: "={{ JSON.stringify($json) }}" }),
      P("waitForResponse", "انتظار پاسخ", "boolean", { default: true }),
      P("timeout", "Timeout (ms)", "number", { default: 5000 }),
    ],
  },
  {
    type: "udp",
    name: "UDP Socket",
    category: "iot",
    icon: "📶",
    color: "#0f766e",
    description: "ارسال دیتاگرام UDP",
    inputs: 1,
    outputs: ["main"],
    handler: "udp",
    params: [
      P("host", "Host", "string", { default: "127.0.0.1" }),
      P("port", "Port", "number", { default: 9001 }),
      P("data", "داده", "string", { default: "={{ JSON.stringify($json) }}" }),
    ],
  },
  {
    type: "mqtt",
    name: "MQTT Client",
    category: "iot",
    icon: "📡",
    color: "#0f766e",
    description: "Publish/Subscribe روی بروکر MQTT (Mosquitto لوکال)",
    inputs: 1,
    outputs: ["main"],
    handler: "mqtt",
    credentialType: "mqtt",
    params: [
      P("brokerUrl", "Broker", "string", { default: "mqtt://localhost:1883" }),
      P("operation", "عملیات", "select", {
        default: "publish",
        options: [
          { value: "publish", label: "Publish" },
          { value: "subscribeOnce", label: "Subscribe (یک پیام)" },
        ],
      }),
      P("topic", "Topic", "string", { default: "flowforge/events" }),
      P("message", "پیام", "string", { default: "={{ JSON.stringify($json) }}" }),
      P("qos", "QoS", "number", { default: 0 }),
    ],
  },
  {
    type: "mqttTrigger",
    name: "MQTT Trigger",
    category: "trigger",
    icon: "📡",
    color: "#0f766e",
    description: "شروع جریان با دریافت پیام MQTT",
    inputs: 0,
    outputs: ["main"],
    trigger: true,
    credentialType: "mqtt",
    handler: "trigger",
    params: [
      P("brokerUrl", "Broker", "string", { default: "mqtt://localhost:1883" }),
      P("topic", "Topic", "string", { default: "sensors/#" }),
    ],
  },
  {
    type: "websocket",
    name: "WebSocket Client",
    category: "iot",
    icon: "🔁",
    color: "#0f766e",
    description: "ارسال پیام و دریافت پاسخ روی WebSocket",
    inputs: 1,
    outputs: ["main"],
    handler: "websocket",
    params: [
      P("url", "آدرس ws://", "string", { default: "ws://localhost:8080" }),
      P("message", "پیام", "string", { default: "={{ JSON.stringify($json) }}" }),
      P("waitForResponse", "انتظار پاسخ", "boolean", { default: true }),
      P("timeout", "Timeout (ms)", "number", { default: 5000 }),
    ],
  },
  {
    type: "websocketTrigger",
    name: "WebSocket Server Trigger",
    category: "trigger",
    icon: "🔁",
    color: "#0f766e",
    description: "شروع جریان با دریافت پیام روی WebSocket Server",
    inputs: 0,
    outputs: ["main"],
    trigger: true,
    handler: "trigger",
    params: [P("port", "Port", "number", { default: 8090 }), P("path", "Path", "string", { default: "/ws" })],
  },
  {
    type: "modbus",
    name: "Modbus TCP",
    category: "iot",
    icon: "🏭",
    color: "#0f766e",
    description: "خواندن/نوشتن رجیسترهای Modbus TCP (دستگاه‌های صنعتی)",
    inputs: 1,
    outputs: ["main"],
    handler: "modbus",
    params: [
      P("host", "Host", "string", { default: "192.168.1.10" }),
      P("port", "Port", "number", { default: 502 }),
      P("unitId", "Unit ID", "number", { default: 1 }),
      P("function", "Function", "select", {
        default: "readHolding",
        options: [
          { value: "readCoils", label: "Read Coils (FC1)" },
          { value: "readDiscrete", label: "Read Discrete Inputs (FC2)" },
          { value: "readHolding", label: "Read Holding Registers (FC3)" },
          { value: "readInput", label: "Read Input Registers (FC4)" },
          { value: "writeCoil", label: "Write Single Coil (FC5)" },
          { value: "writeRegister", label: "Write Single Register (FC6)" },
        ],
      }),
      P("address", "آدرس شروع", "number", { default: 0 }),
      P("quantity", "تعداد", "number", { default: 2 }),
      P("value", "مقدار (برای نوشتن)", "number", { default: 0 }),
    ],
  },
  {
    type: "ftp",
    name: "FTP / SFTP",
    category: "storage",
    icon: "📂",
    color: "#0891b2",
    description: "آپلود/دانلود/لیست فایل روی FTP/SFTP",
    inputs: 1,
    outputs: ["main"],
    handler: "genericApi",
    credentialType: "ftp",
    params: [
      P("protocol", "پروتکل", "select", {
        default: "sftp",
        options: [
          { value: "ftp", label: "FTP" },
          { value: "sftp", label: "SFTP" },
        ],
      }),
      P("operation", "عملیات", "select", {
        default: "list",
        options: [
          { value: "list", label: "List" },
          { value: "download", label: "Download" },
          { value: "upload", label: "Upload" },
          { value: "delete", label: "Delete" },
        ],
      }),
      P("path", "مسیر", "string", { default: "/" }),
    ],
  },
  {
    type: "s3",
    name: "S3 / MinIO",
    category: "storage",
    icon: "🪣",
    color: "#c2410c",
    description: "عملیات روی Object Storage سازگار با S3",
    inputs: 1,
    outputs: ["main"],
    handler: "s3",
    credentialType: "s3",
    params: [
      P("operation", "عملیات", "select", {
        default: "list",
        options: [
          { value: "list", label: "List Objects" },
          { value: "get", label: "Get Object" },
          { value: "put", label: "Put Object" },
          { value: "delete", label: "Delete Object" },
        ],
      }),
      P("bucket", "Bucket", "string", { default: "flowforge" }),
      P("key", "Key", "string", { default: "={{ $json.key }}" }),
      P("content", "محتوا (Put)", "textarea", { default: "={{ JSON.stringify($json) }}" }),
    ],
  },
  {
    type: "logStream",
    name: "Log Stream",
    category: "devops",
    icon: "📤",
    color: "#64748b",
    description: "ارسال لاگ به Datadog / ELK / Loki / Webhook",
    inputs: 1,
    outputs: ["main"],
    handler: "logStream",
    params: [
      P("destination", "مقصد", "select", {
        default: "console",
        options: [
          { value: "console", label: "Console" },
          { value: "webhook", label: "HTTP Webhook" },
          { value: "datadog", label: "Datadog" },
          { value: "elastic", label: "Elasticsearch" },
          { value: "loki", label: "Grafana Loki" },
        ],
      }),
      P("url", "آدرس", "string"),
      P("level", "سطح", "select", {
        default: "info",
        options: ["debug", "info", "warn", "error"].map((l) => ({ value: l, label: l })),
      }),
      P("message", "پیام", "string", { default: "={{ JSON.stringify($json) }}" }),
    ],
  },
];

// ---------------------------------------------------------------------------
// یکپارچه‌سازی‌ها – هر مورد به چند نود (منابع + تریگر) گسترش می‌یابد
// [name, icon, category, baseUrl, resources[], hasTrigger]
// ---------------------------------------------------------------------------
type IntegrationSpec = [string, string, string, string, string[], boolean];

const INTEGRATIONS: IntegrationSpec[] = [
  // Messaging
  ["Microsoft Teams", "👥", "messaging", "https://graph.microsoft.com/v1.0", ["Channel Message", "Chat Message", "Team", "Task"], true],
  ["Mattermost", "💬", "messaging", "", ["Post", "Channel", "User", "Reaction"], true],
  ["WhatsApp Business", "📲", "messaging", "https://graph.facebook.com/v19.0", ["Message", "Template", "Media"], true],
  ["Twilio", "📞", "messaging", "https://api.twilio.com/2010-04-01", ["SMS", "Voice Call", "WhatsApp"], true],
  ["Rocket.Chat", "🚀", "messaging", "", ["Message", "Channel"], true],
  ["Zulip", "💭", "messaging", "", ["Message", "Stream", "User"], false],
  ["Matrix", "🟩", "messaging", "", ["Message", "Room", "Media"], true],
  ["Signal", "🔒", "messaging", "", ["Message"], true],
  ["Line", "🟢", "messaging", "https://api.line.me/v2", ["Message", "Profile"], true],
  ["Viber", "🟣", "messaging", "https://chatapi.viber.com/pa", ["Message"], true],
  ["Pushover", "🔔", "messaging", "https://api.pushover.net/1", ["Notification"], false],
  ["Pushbullet", "🔔", "messaging", "https://api.pushbullet.com/v2", ["Push"], false],
  ["Gotify", "🔔", "messaging", "", ["Message"], false],
  ["ntfy", "🔔", "messaging", "https://ntfy.sh", ["Publish"], false],
  ["Kavenegar SMS", "📨", "messaging", "https://api.kavenegar.com/v1", ["SMS", "Verify Lookup"], false],
  ["SMS.ir", "📨", "messaging", "https://api.sms.ir/v1", ["SMS", "Verify"], false],
  ["Ghasedak SMS", "📨", "messaging", "https://api.ghasedak.me/v2", ["SMS"], false],
  ["Eitaa", "🟠", "messaging", "https://eitaayar.ir/api", ["Message", "File"], false],
  ["iGap", "🟣", "messaging", "", ["Message"], true],
  ["Rubika", "🔴", "messaging", "", ["Message", "Channel Post"], true],

  // Email
  ["Gmail", "📧", "email", "https://gmail.googleapis.com/gmail/v1", ["Message", "Draft", "Label", "Thread"], true],
  ["Outlook", "📧", "email", "https://graph.microsoft.com/v1.0", ["Message", "Draft", "Folder", "Calendar"], true],
  ["SendGrid", "📧", "email", "https://api.sendgrid.com/v3", ["Mail", "Contact", "List"], false],
  ["Mailgun", "📧", "email", "https://api.mailgun.net/v3", ["Message", "Domain"], false],
  ["Amazon SES", "📧", "email", "https://email.us-east-1.amazonaws.com", ["Email", "Template"], false],
  ["Postmark", "📧", "email", "https://api.postmarkapp.com", ["Email", "Template"], true],
  ["IMAP", "📥", "email", "", ["Message", "Mailbox"], true],
  ["Mailjet", "📧", "email", "https://api.mailjet.com/v3.1", ["Email", "SMS"], true],

  // Productivity
  ["Jira", "🟦", "productivity", "", ["Issue", "Issue Comment", "Project", "User", "Sprint"], true],
  ["Trello", "📋", "productivity", "https://api.trello.com/1", ["Card", "Board", "List", "Checklist", "Label"], true],
  ["Asana", "🔺", "productivity", "https://app.asana.com/api/1.0", ["Task", "Project", "Subtask", "User"], true],
  ["Monday.com", "🟪", "productivity", "https://api.monday.com/v2", ["Board", "Item", "Column", "Update"], true],
  ["ClickUp", "✅", "productivity", "https://api.clickup.com/api/v2", ["Task", "List", "Folder", "Comment", "Goal"], true],
  ["Linear", "📐", "productivity", "https://api.linear.app/graphql", ["Issue", "Project", "Cycle", "Comment"], true],
  ["Notion", "📓", "productivity", "https://api.notion.com/v1", ["Page", "Database", "Database Page", "Block", "User"], true],
  ["Todoist", "✔️", "productivity", "https://api.todoist.com/rest/v2", ["Task", "Project", "Section", "Label"], true],
  ["Evernote", "🐘", "productivity", "", ["Note", "Notebook", "Tag"], false],
  ["Airtable", "🟨", "productivity", "https://api.airtable.com/v0", ["Record", "Base", "Table"], true],
  ["Coda", "📄", "productivity", "https://coda.io/apis/v1", ["Table Row", "Doc", "Formula"], false],
  ["Basecamp", "🏕️", "productivity", "", ["Todo", "Message", "Project"], true],
  ["Wrike", "🟩", "productivity", "https://www.wrike.com/api/v4", ["Task", "Folder", "Comment"], true],
  ["Confluence", "📘", "productivity", "", ["Page", "Space", "Comment"], false],
  ["Obsidian (Local)", "💎", "productivity", "", ["Note"], true],
  ["Calendly", "📆", "productivity", "https://api.calendly.com", ["Event", "Invitee"], true],
  ["Cal.com", "📆", "productivity", "https://api.cal.com/v1", ["Booking", "Event Type"], true],
  ["Google Keep", "🗒️", "productivity", "", ["Note"], false],
  ["Miro", "🖼️", "productivity", "https://api.miro.com/v2", ["Board", "Item"], false],
  ["Figma", "🎨", "productivity", "https://api.figma.com/v1", ["File", "Comment"], true],
  ["Typeform", "📝", "productivity", "https://api.typeform.com", ["Form", "Response"], true],
  ["Jotform", "📝", "productivity", "https://api.jotform.com", ["Form", "Submission"], true],
  ["Tally", "📝", "productivity", "https://api.tally.so", ["Form", "Submission"], true],
  ["Google Forms", "📝", "google", "https://forms.googleapis.com/v1", ["Form", "Response"], true],

  // Google
  ["Google Sheets", "📊", "google", "https://sheets.googleapis.com/v4", ["Sheet Row", "Sheet", "Spreadsheet"], true],
  ["Google Drive", "📁", "google", "https://www.googleapis.com/drive/v3", ["File", "Folder", "Shared Drive", "Permission"], true],
  ["Google Calendar", "📅", "google", "https://www.googleapis.com/calendar/v3", ["Event", "Calendar"], true],
  ["Google Docs", "📄", "google", "https://docs.googleapis.com/v1", ["Document"], false],
  ["Google Slides", "📽️", "google", "https://slides.googleapis.com/v1", ["Presentation", "Page"], false],
  ["Google Tasks", "☑️", "google", "https://tasks.googleapis.com/tasks/v1", ["Task", "Task List"], false],
  ["Google Analytics", "📈", "google", "https://analyticsdata.googleapis.com/v1beta", ["Report", "User Activity"], false],
  ["Google BigQuery", "🧮", "google", "https://bigquery.googleapis.com/bigquery/v2", ["Query", "Table", "Dataset"], false],
  ["Google Contacts", "👤", "google", "https://people.googleapis.com/v1", ["Contact"], false],
  ["Google Cloud Storage", "☁️", "google", "https://storage.googleapis.com/storage/v1", ["Object", "Bucket"], false],
  ["Google Translate", "🌐", "google", "https://translation.googleapis.com/language/translate/v2", ["Language"], false],
  ["Google Vision", "👁️", "google", "https://vision.googleapis.com/v1", ["Image"], false],
  ["YouTube", "▶️", "google", "https://www.googleapis.com/youtube/v3", ["Video", "Channel", "Playlist", "Comment"], true],
  ["Google Ads", "📢", "google", "https://googleads.googleapis.com/v16", ["Campaign", "Report"], false],
  ["Google Business Profile", "🏪", "google", "https://mybusiness.googleapis.com/v4", ["Post", "Review"], true],
  ["Google Chat", "💬", "google", "https://chat.googleapis.com/v1", ["Message", "Space"], true],
  ["Firebase", "🔥", "google", "", ["Realtime Database", "Firestore Document", "Cloud Messaging"], true],
  ["Gemini", "✨", "ai", "https://generativelanguage.googleapis.com/v1beta", ["Text", "Vision", "Embedding"], false],

  // Microsoft
  ["Microsoft Excel", "📗", "microsoft", "https://graph.microsoft.com/v1.0", ["Table Row", "Worksheet", "Workbook"], false],
  ["OneDrive", "☁️", "microsoft", "https://graph.microsoft.com/v1.0", ["File", "Folder"], true],
  ["SharePoint", "🏢", "microsoft", "https://graph.microsoft.com/v1.0", ["List Item", "File", "Site"], true],
  ["Microsoft Dynamics 365", "🟦", "microsoft", "", ["Account", "Contact", "Lead", "Opportunity"], false],
  ["Microsoft SQL", "🗄️", "database", "", ["Query", "Table"], false],
  ["Microsoft Entra ID", "🪪", "microsoft", "https://graph.microsoft.com/v1.0", ["User", "Group"], false],
  ["Microsoft To Do", "☑️", "microsoft", "https://graph.microsoft.com/v1.0", ["Task", "List"], false],
  ["Microsoft OneNote", "📓", "microsoft", "https://graph.microsoft.com/v1.0", ["Page", "Notebook"], false],
  ["Microsoft Power BI", "📊", "microsoft", "https://api.powerbi.com/v1.0/myorg", ["Dataset", "Report"], false],
  ["Azure OpenAI", "🤖", "ai", "", ["Chat", "Embedding"], false],
  ["Azure Blob Storage", "🪣", "microsoft", "", ["Blob", "Container"], false],
  ["Azure DevOps", "🛠️", "devops", "https://dev.azure.com", ["Work Item", "Pipeline", "Repository"], true],

  // CRM
  ["HubSpot", "🟠", "crm", "https://api.hubapi.com", ["Contact", "Company", "Deal", "Ticket", "Engagement"], true],
  ["Salesforce", "☁️", "crm", "", ["Lead", "Contact", "Account", "Opportunity", "Case", "Custom Object"], true],
  ["Pipedrive", "🟢", "crm", "https://api.pipedrive.com/v1", ["Deal", "Person", "Organization", "Activity", "Note"], true],
  ["Zoho CRM", "🔴", "crm", "https://www.zohoapis.com/crm/v3", ["Lead", "Contact", "Account", "Deal"], true],
  ["ActiveCampaign", "🔵", "crm", "", ["Contact", "Deal", "Account", "Tag"], true],
  ["Freshsales", "🟢", "crm", "", ["Lead", "Contact", "Deal"], false],
  ["Copper", "🟤", "crm", "https://api.copper.com/developer_api/v1", ["Lead", "Person", "Opportunity"], true],
  ["Keap", "🟢", "crm", "https://api.infusionsoft.com/crm/rest/v1", ["Contact", "Company"], true],
  ["Agile CRM", "🔵", "crm", "", ["Contact", "Deal", "Company"], false],
  ["Odoo", "🟪", "crm", "", ["Contact", "Opportunity", "Note", "Custom Resource"], false],
  ["Didar CRM", "🟢", "crm", "https://app.didar.me/api", ["Contact", "Deal"], false],
  ["Attio", "⚫", "crm", "https://api.attio.com/v2", ["Record", "List"], true],
  ["Close", "🟢", "crm", "https://api.close.com/api/v1", ["Lead", "Contact", "Opportunity"], true],

  // Marketing
  ["Mailchimp", "🐵", "marketing", "", ["Member", "List", "Campaign", "Tag"], true],
  ["Brevo", "🟢", "marketing", "https://api.brevo.com/v3", ["Contact", "Email", "Attribute"], true],
  ["ConvertKit", "🟥", "marketing", "https://api.convertkit.com/v3", ["Subscriber", "Form", "Sequence", "Tag"], true],
  ["GetResponse", "🔵", "marketing", "https://api.getresponse.com/v3", ["Contact", "Campaign"], false],
  ["MailerLite", "🟢", "marketing", "https://connect.mailerlite.com/api", ["Subscriber", "Group"], true],
  ["Customer.io", "🟠", "marketing", "https://track.customer.io/api/v1", ["Customer", "Event", "Campaign"], false],
  ["Klaviyo", "⚫", "marketing", "https://a.klaviyo.com/api", ["Profile", "Event", "List"], false],
  ["Lemlist", "🟣", "marketing", "https://api.lemlist.com/api", ["Lead", "Campaign"], true],
  ["Facebook Graph API", "🔵", "marketing", "https://graph.facebook.com/v19.0", ["Page Post", "Lead Ad", "Insights"], true],
  ["Facebook Lead Ads", "🔵", "marketing", "https://graph.facebook.com/v19.0", ["Lead"], true],
  ["LinkedIn", "🔷", "social", "https://api.linkedin.com/v2", ["Post", "Profile"], false],
  ["X (Twitter)", "⚫", "social", "https://api.twitter.com/2", ["Tweet", "User", "Direct Message"], false],
  ["Instagram", "📸", "social", "https://graph.facebook.com/v19.0", ["Media", "Comment"], false],
  ["Reddit", "🟠", "social", "https://oauth.reddit.com", ["Post", "Comment", "Subreddit"], false],
  ["Mastodon", "🐘", "social", "", ["Status", "Account"], false],
  ["Bluesky", "🦋", "social", "https://bsky.social/xrpc", ["Post", "Profile"], false],
  ["Pinterest", "📌", "social", "https://api.pinterest.com/v5", ["Pin", "Board"], false],
  ["TikTok", "🎵", "social", "https://open.tiktokapis.com/v2", ["Video", "User"], false],
  ["Aparat", "🎬", "social", "https://www.aparat.com/etc/api", ["Video", "Channel"], false],
  ["Medium", "✍️", "social", "https://api.medium.com/v1", ["Post", "Publication"], false],
  ["WordPress", "🅦", "social", "", ["Post", "Page", "User", "Media"], true],
  ["Ghost", "👻", "social", "", ["Post", "Member"], true],
  ["Webflow", "🌊", "social", "https://api.webflow.com/v2", ["Item", "Collection"], true],
  ["Strapi", "🟣", "social", "", ["Entry"], false],
  ["Contentful", "📦", "social", "https://api.contentful.com", ["Entry", "Asset"], true],

  // Databases
  ["MySQL", "🐬", "database", "", ["Query", "Table", "Insert", "Update"], true],
  ["MariaDB", "🦭", "database", "", ["Query", "Table"], false],
  ["MongoDB", "🍃", "database", "", ["Document", "Aggregate", "Collection"], true],
  ["SQLite", "🪶", "database", "", ["Query", "Table"], false],
  ["Supabase", "⚡", "database", "", ["Row", "Storage Object", "Auth User", "RPC"], true],
  ["Redis", "🟥", "database", "", ["Key", "Hash", "List", "Pub/Sub", "Stream"], true],
  ["Elasticsearch", "🔍", "database", "", ["Document", "Index", "Search"], false],
  ["ClickHouse", "🟡", "database", "", ["Query", "Insert"], false],
  ["CockroachDB", "🪳", "database", "", ["Query"], false],
  ["TimescaleDB", "⏱️", "database", "", ["Query", "Hypertable"], false],
  ["InfluxDB", "📈", "database", "", ["Write Point", "Query (Flux)"], false],
  ["Cassandra", "👁️", "database", "", ["Query"], false],
  ["Neo4j", "🕸️", "database", "", ["Cypher Query", "Node", "Relationship"], false],
  ["DynamoDB", "🟧", "database", "", ["Item", "Table", "Query"], false],
  ["Snowflake", "❄️", "database", "", ["Query"], false],
  ["Oracle DB", "🔴", "database", "", ["Query"], false],
  ["CrateDB", "🟦", "database", "", ["Query"], false],
  ["QuestDB", "🟠", "database", "", ["Query"], false],
  ["PocketBase", "📦", "database", "", ["Record", "Collection"], true],
  ["NocoDB", "📊", "database", "", ["Row", "Table"], true],
  ["Baserow", "📊", "database", "", ["Row", "Table"], true],
  ["SeaTable", "📊", "database", "", ["Row", "Table"], true],

  // Vector
  ["Pinecone", "🌲", "vector", "", ["Vector Upsert", "Vector Query", "Index"], false],
  ["Weaviate", "🟩", "vector", "", ["Object", "Query", "Class"], false],
  ["Milvus", "🔷", "vector", "", ["Vector Insert", "Vector Search", "Collection"], false],
  ["Qdrant", "🟥", "vector", "", ["Point Upsert", "Point Search", "Collection"], false],
  ["Chroma", "🎨", "vector", "", ["Document", "Query", "Collection"], false],
  ["pgvector", "🐘", "vector", "", ["Vector Insert", "Similarity Search"], false],
  ["Redis Vector", "🟥", "vector", "", ["Vector", "Search"], false],
  ["Zep Memory", "🧠", "vector", "", ["Session", "Memory"], false],

  // AI providers
  ["OpenAI", "🤖", "ai", "https://api.openai.com/v1", ["Chat", "Image", "Audio (Whisper/TTS)", "Assistant", "Embedding", "Moderation"], false],
  ["Anthropic Claude", "🟤", "ai", "https://api.anthropic.com/v1", ["Message", "Tool Use"], false],
  ["Ollama", "🦙", "ai", "http://localhost:11434", ["Chat", "Generate", "Embedding", "Model"], false],
  ["Mistral AI", "🌬️", "ai", "https://api.mistral.ai/v1", ["Chat", "Embedding"], false],
  ["Cohere", "🟪", "ai", "https://api.cohere.com/v1", ["Chat", "Rerank", "Embed"], false],
  ["Groq", "⚡", "ai", "https://api.groq.com/openai/v1", ["Chat"], false],
  ["OpenRouter", "🔀", "ai", "https://openrouter.ai/api/v1", ["Chat"], false],
  ["Hugging Face", "🤗", "ai", "https://api-inference.huggingface.co", ["Inference", "Model"], false],
  ["Replicate", "🔁", "ai", "https://api.replicate.com/v1", ["Prediction", "Model"], false],
  ["Stability AI", "🎨", "ai", "https://api.stability.ai/v2beta", ["Image Generate", "Upscale"], false],
  ["ElevenLabs", "🎙️", "ai", "https://api.elevenlabs.io/v1", ["Text to Speech", "Voice"], false],
  ["Deepgram", "🎧", "ai", "https://api.deepgram.com/v1", ["Transcribe"], false],
  ["AssemblyAI", "🎧", "ai", "https://api.assemblyai.com/v2", ["Transcript"], false],
  ["DeepSeek", "🐋", "ai", "https://api.deepseek.com/v1", ["Chat"], false],
  ["xAI Grok", "❌", "ai", "https://api.x.ai/v1", ["Chat"], false],
  ["Perplexity", "🔮", "ai", "https://api.perplexity.ai", ["Chat (Search)"], false],
  ["LM Studio", "🖥️", "ai", "http://localhost:1234/v1", ["Chat", "Embedding"], false],
  ["LocalAI", "🏠", "ai", "http://localhost:8080/v1", ["Chat", "Image", "Embedding"], false],
  ["Jina AI", "🟨", "ai", "https://api.jina.ai/v1", ["Reader", "Embedding", "Rerank"], false],
  ["Tavily Search", "🔎", "ai", "https://api.tavily.com", ["Search", "Extract"], false],
  ["SerpAPI", "🔎", "ai", "https://serpapi.com", ["Search"], false],
  ["Firecrawl", "🔥", "ai", "https://api.firecrawl.dev/v1", ["Scrape", "Crawl"], false],

  // Storage
  ["Dropbox", "📦", "storage", "https://api.dropboxapi.com/2", ["File", "Folder", "Shared Link"], true],
  ["Nextcloud", "☁️", "storage", "", ["File", "Folder", "User", "Talk Message"], true],
  ["Seafile", "🌊", "storage", "", ["File", "Library"], false],
  ["Box", "📦", "storage", "https://api.box.com/2.0", ["File", "Folder"], true],
  ["MinIO", "🪣", "storage", "", ["Object", "Bucket"], true],
  ["Backblaze B2", "🟥", "storage", "https://api.backblazeb2.com/b2api/v2", ["File", "Bucket"], false],
  ["Cloudflare R2", "🟧", "storage", "", ["Object", "Bucket"], false],
  ["WebDAV", "📂", "storage", "", ["File", "Folder"], false],
  ["Local Filesystem", "💽", "storage", "", ["File", "Directory"], true],

  // DevOps
  ["GitHub", "🐙", "devops", "https://api.github.com", ["Issue", "Pull Request", "Repository", "Release", "File", "Workflow Dispatch"], true],
  ["GitLab", "🦊", "devops", "https://gitlab.com/api/v4", ["Issue", "Merge Request", "Project", "Pipeline", "File"], true],
  ["Bitbucket", "🪣", "devops", "https://api.bitbucket.org/2.0", ["Issue", "Pull Request", "Repository"], true],
  ["Gitea", "🍵", "devops", "", ["Issue", "Pull Request", "Repository"], true],
  ["Docker", "🐳", "devops", "http://localhost:2375", ["Container", "Image", "Volume", "Network"], true],
  ["Kubernetes", "☸️", "devops", "", ["Pod", "Deployment", "Job", "ConfigMap", "Secret"], true],
  ["Portainer", "🐳", "devops", "", ["Stack", "Container"], false],
  ["PagerDuty", "🚨", "devops", "https://api.pagerduty.com", ["Incident", "Log Entry", "User"], true],
  ["ServiceNow", "🟩", "devops", "", ["Incident", "Table Record", "User"], false],
  ["Opsgenie", "🔔", "devops", "https://api.opsgenie.com/v2", ["Alert"], true],
  ["Sentry", "🛡️", "devops", "https://sentry.io/api/0", ["Issue", "Event", "Release"], true],
  ["Grafana", "📊", "devops", "", ["Dashboard", "Alert", "Annotation"], true],
  ["Prometheus", "🔥", "devops", "", ["Query", "Alert"], true],
  ["Datadog", "🐶", "devops", "https://api.datadoghq.com/api/v1", ["Event", "Metric", "Log", "Monitor"], true],
  ["New Relic", "🟢", "devops", "https://api.newrelic.com/v2", ["Event", "Alert"], false],
  ["Jenkins", "🧑‍🔧", "devops", "", ["Job", "Build"], true],
  ["CircleCI", "🟢", "devops", "https://circleci.com/api/v2", ["Pipeline", "Workflow"], false],
  ["Travis CI", "🟢", "devops", "https://api.travis-ci.com", ["Build"], false],
  ["Vercel", "▲", "devops", "https://api.vercel.com", ["Deployment", "Project"], true],
  ["Netlify", "🟩", "devops", "https://api.netlify.com/api/v1", ["Site", "Deploy"], true],
  ["Cloudflare", "🟧", "devops", "https://api.cloudflare.com/client/v4", ["DNS Record", "Zone", "Worker", "KV"], false],
  ["AWS Lambda", "λ", "devops", "", ["Invoke Function"], false],
  ["AWS S3", "🪣", "storage", "", ["Object", "Bucket"], false],
  ["AWS SQS", "📬", "devops", "", ["Message", "Queue"], true],
  ["AWS SNS", "📣", "devops", "", ["Publish", "Topic"], true],
  ["AWS EC2", "🖥️", "devops", "", ["Instance"], false],
  ["AWS Secrets Manager", "🔐", "devops", "", ["Secret"], false],
  ["HashiCorp Vault", "🔐", "devops", "", ["Secret", "KV", "Transit"], false],
  ["Terraform Cloud", "🟪", "devops", "https://app.terraform.io/api/v2", ["Run", "Workspace"], false],
  ["Ansible AWX", "🔴", "devops", "", ["Job Template", "Inventory"], false],
  ["RabbitMQ", "🐇", "devops", "", ["Message", "Queue", "Exchange"], true],
  ["Apache Kafka", "📨", "devops", "", ["Message", "Topic"], true],
  ["NATS", "📨", "devops", "", ["Message", "Subject"], true],
  ["Uptime Kuma", "🟢", "devops", "", ["Monitor", "Heartbeat"], true],
  ["SSH", "🔑", "devops", "", ["Command", "File Transfer"], false],
  ["Home Assistant", "🏠", "iot", "", ["Service", "State", "Event", "Template"], true],
  ["Node-RED", "🔴", "iot", "", ["Flow", "Message"], true],
  ["Zigbee2MQTT", "📡", "iot", "", ["Device", "Group"], true],
  ["OPC UA", "🏭", "iot", "", ["Read Node", "Write Node", "Subscribe"], true],
  ["BACnet", "🏢", "iot", "", ["Read Property", "Write Property"], false],
  ["SNMP", "📶", "iot", "", ["Get", "Set", "Walk"], true],
  ["Serial Port", "🔌", "iot", "", ["Write", "Read"], true],
  ["Philips Hue", "💡", "iot", "", ["Light", "Group", "Scene"], false],
  ["Tasmota", "💡", "iot", "", ["Command", "Status"], true],
  ["ESPHome", "🔌", "iot", "", ["Entity", "Service"], true],

  // Ecommerce & Finance
  ["Shopify", "🛍️", "ecommerce", "", ["Order", "Product", "Customer", "Inventory", "Fulfillment"], true],
  ["WooCommerce", "🟣", "ecommerce", "", ["Order", "Product", "Customer", "Coupon"], true],
  ["Amazon Seller", "📦", "ecommerce", "https://sellingpartnerapi-na.amazon.com", ["Order", "Inventory", "Report"], false],
  ["Magento", "🟠", "ecommerce", "", ["Order", "Product", "Customer"], true],
  ["PrestaShop", "🩷", "ecommerce", "", ["Order", "Product"], true],
  ["Digikala Seller", "🔴", "ecommerce", "https://seller.digikala.com/api/v1", ["Order", "Product", "Variant"], false],
  ["Torob", "🟦", "ecommerce", "", ["Product"], false],
  ["Basalam", "🟢", "ecommerce", "https://openapi.basalam.com", ["Product", "Order"], true],
  ["Stripe", "💳", "finance", "https://api.stripe.com/v1", ["Charge", "Customer", "Payment Intent", "Subscription", "Invoice", "Balance"], true],
  ["PayPal", "🅿️", "finance", "https://api-m.paypal.com/v2", ["Payment", "Payout", "Order"], true],
  ["Zarinpal", "💛", "finance", "https://payment.zarinpal.com/pg/v4", ["Payment Request", "Verify"], false],
  ["IDPay", "💙", "finance", "https://api.idpay.ir/v1.1", ["Payment", "Verify"], false],
  ["Zibal", "💜", "finance", "https://gateway.zibal.ir", ["Payment", "Verify", "Inquiry"], false],
  ["PayPing", "💚", "finance", "https://api.payping.ir/v2", ["Payment", "Verify"], false],
  ["Wise", "💚", "finance", "https://api.wise.com/v1", ["Transfer", "Quote"], true],
  ["QuickBooks", "🟩", "finance", "", ["Invoice", "Customer", "Payment", "Bill"], true],
  ["Xero", "🔵", "finance", "https://api.xero.com/api.xro/2.0", ["Invoice", "Contact"], true],
  ["Invoice Ninja", "🥷", "finance", "", ["Invoice", "Client", "Payment"], true],
  ["Coinbase", "🟦", "finance", "https://api.coinbase.com/v2", ["Account", "Transaction"], true],
  ["Binance", "🟨", "finance", "https://api.binance.com/api/v3", ["Ticker", "Order", "Account"], false],
  ["Nobitex", "🟦", "finance", "https://api.nobitex.ir", ["Market", "Order", "Wallet"], false],
  ["CoinGecko", "🦎", "finance", "https://api.coingecko.com/api/v3", ["Coin", "Price"], false],
  ["Open Exchange Rates", "💱", "finance", "https://openexchangerates.org/api", ["Rates"], false],
  ["Tether/Crypto Price", "₮", "finance", "https://api.coinpaprika.com/v1", ["Ticker"], false],

  // Support & HR
  ["Zendesk", "🟩", "support", "", ["Ticket", "User", "Organization"], true],
  ["Freshdesk", "🟢", "support", "", ["Ticket", "Contact"], true],
  ["Intercom", "💬", "support", "https://api.intercom.io", ["Contact", "Conversation", "Company"], true],
  ["Help Scout", "🔵", "support", "https://api.helpscout.net/v2", ["Conversation", "Customer"], true],
  ["Crisp", "💬", "support", "https://api.crisp.chat/v1", ["Conversation", "People"], true],
  ["Chatwoot", "💬", "support", "", ["Conversation", "Contact", "Message"], true],
  ["Drift", "💬", "support", "https://driftapi.com", ["Contact", "Conversation"], true],
  ["Tawk.to", "💬", "support", "https://api.tawk.to/v1", ["Chat"], true],
  ["BambooHR", "🎋", "hr", "", ["Employee", "Time Off", "Report"], true],
  ["Workable", "🟦", "hr", "https://www.workable.com/spi/v3", ["Candidate", "Job"], true],
  ["Greenhouse", "🟩", "hr", "https://harvest.greenhouse.io/v1", ["Candidate", "Application"], true],
  ["Personio", "🟪", "hr", "https://api.personio.de/v1", ["Employee", "Absence"], false],
  ["Gusto", "🟠", "hr", "https://api.gusto.com/v1", ["Employee", "Payroll"], false],
  ["Zoom", "📹", "productivity", "https://api.zoom.us/v2", ["Meeting", "Webinar", "Recording"], true],
  ["Google Meet", "📹", "google", "https://meet.googleapis.com/v2", ["Space", "Conference"], false],
  ["Jitsi", "📹", "productivity", "", ["Meeting"], false],
  ["Skyroom", "📹", "productivity", "https://www.skyroom.online/skyroom/api", ["Room", "User"], false],

  // Analytics & Misc
  ["Mixpanel", "📊", "analytics", "https://api.mixpanel.com", ["Event", "Profile"], false],
  ["Amplitude", "📈", "analytics", "https://api2.amplitude.com", ["Event"], false],
  ["PostHog", "🦔", "analytics", "", ["Event", "Person", "Feature Flag"], true],
  ["Plausible", "📊", "analytics", "https://plausible.io/api/v1", ["Stats"], false],
  ["Matomo", "📊", "analytics", "", ["Report", "Event"], false],
  ["Segment", "🟩", "analytics", "https://api.segment.io/v1", ["Track", "Identify", "Group"], false],
  ["Metabase", "📊", "analytics", "", ["Question", "Card"], false],
  ["Apache Superset", "📊", "analytics", "", ["Chart", "Dashboard"], false],
  ["Airbyte", "🔄", "analytics", "", ["Connection", "Sync"], false],
  ["dbt Cloud", "🟧", "analytics", "https://cloud.getdbt.com/api/v2", ["Job", "Run"], false],
  ["OpenWeatherMap", "🌦️", "misc", "https://api.openweathermap.org/data/2.5", ["Current Weather", "Forecast"], false],
  ["NASA", "🚀", "misc", "https://api.nasa.gov", ["APOD", "Mars Rover"], false],
  ["Wikipedia", "📖", "misc", "https://en.wikipedia.org/api/rest_v1", ["Page Summary", "Search"], false],
  ["Google Maps", "🗺️", "google", "https://maps.googleapis.com/maps/api", ["Geocode", "Directions", "Places"], false],
  ["Neshan Maps", "🗺️", "misc", "https://api.neshan.org/v1", ["Geocode", "Routing", "Search"], false],
  ["Cedar Maps", "🗺️", "misc", "https://api.cedarmaps.com/v1", ["Geocode", "Direction"], false],
  ["Balad Maps", "🗺️", "misc", "https://api.balad.ir", ["Search", "Route"], false],
  ["OpenStreetMap", "🗺️", "misc", "https://nominatim.openstreetmap.org", ["Geocode", "Reverse"], false],
  ["Divar", "🔴", "misc", "https://api.divar.ir/v1/open-platform", ["Post", "Chat"], true],
  ["Snapp", "🟢", "misc", "", ["Ride Estimate"], false],
  ["Alibaba Travel", "🟡", "misc", "", ["Flight Search", "Hotel"], false],
  ["Sabte Ahval (Inquiry)", "🪪", "misc", "", ["National ID Inquiry"], false],
  ["Post (Iran Post)", "📮", "misc", "", ["Tracking", "Tariff"], false],
  ["Tipax", "📦", "misc", "", ["Shipment", "Tracking"], false],
  ["Google reCAPTCHA", "🤖", "misc", "https://www.google.com/recaptcha/api", ["Verify"], false],
  ["Cloudflare Turnstile", "🟧", "misc", "https://challenges.cloudflare.com/turnstile/v0", ["Verify"], false],
  ["Bitly", "🔗", "misc", "https://api-ssl.bitly.com/v4", ["Link"], false],
  ["Yourls", "🔗", "misc", "", ["Short URL"], false],
  ["QR Code", "▦", "misc", "https://api.qrserver.com/v1", ["Generate"], false],
  ["Cron Job (External)", "⏰", "misc", "https://api.cron-job.org", ["Job"], true],
  ["Uptime Robot", "🤖", "devops", "https://api.uptimerobot.com/v2", ["Monitor", "Alert Contact"], false],
  ["PDF Generator", "📄", "files", "", ["HTML to PDF", "Merge PDF", "Extract Text"], false],
  ["Image Processing", "🖼️", "files", "", ["Resize", "Crop", "Convert", "Watermark"], false],
  ["FFmpeg", "🎞️", "files", "", ["Transcode", "Extract Audio", "Thumbnail"], false],
  ["Tesseract OCR", "🔤", "files", "", ["Recognize Text"], false],
  ["LibreOffice Convert", "📄", "files", "", ["Convert Document"], false],
  ["Excel (xlsx)", "📗", "files", "", ["Read", "Write"], false],
  ["CSV", "📊", "files", "", ["Parse", "Generate"], false],
  ["Zip/Unzip", "🗜️", "files", "", ["Compress", "Extract"], false],
  ["LDAP", "🪪", "misc", "", ["Search", "User", "Group"], false],
  ["SAML SSO", "🔐", "misc", "", ["Assertion"], false],
  ["Keycloak", "🔐", "misc", "", ["User", "Role", "Client"], true],
  ["Authentik", "🔐", "misc", "", ["User", "Group"], true],
  ["Auth0", "🔐", "misc", "", ["User", "Role", "Log"], true],
  ["OneSignal", "🔔", "messaging", "https://onesignal.com/api/v1", ["Notification", "Player"], false],
  ["Firebase Cloud Messaging", "🔔", "messaging", "https://fcm.googleapis.com/v1", ["Message"], false],
  ["Web Push", "🔔", "messaging", "", ["Notification"], false],
  ["Spotify", "🎵", "misc", "https://api.spotify.com/v1", ["Track", "Playlist", "Player"], false],
  ["Plex", "🎬", "misc", "", ["Library", "Playback"], true],
  ["Jellyfin", "🎬", "misc", "", ["Item", "Session"], true],
  ["Transmission", "⬇️", "misc", "", ["Torrent"], false],
  ["qBittorrent", "⬇️", "misc", "", ["Torrent"], false],
  ["Steam", "🎮", "misc", "https://api.steampowered.com", ["Player", "Game"], false],
  ["Twitch", "🟣", "social", "https://api.twitch.tv/helix", ["Stream", "Channel", "Clip"], true],
  ["Zapier (Bridge)", "⚡", "misc", "https://hooks.zapier.com", ["Zap Trigger"], false],
  ["Make (Bridge)", "🟣", "misc", "https://hook.eu1.make.com", ["Scenario Trigger"], false],
  ["IFTTT", "🟥", "misc", "https://maker.ifttt.com/trigger", ["Event"], false],
  ["n8n (Bridge)", "🟠", "misc", "", ["Workflow", "Execution"], true],
];

const slug = (s: string) =>
  s
    .replace(/\(.*?\)/g, "")
    .replace(/[^a-zA-Z0-9 ]/g, "")
    .trim()
    .split(/\s+/)
    .map((w, i) => (i === 0 ? w.toLowerCase() : w[0].toUpperCase() + w.slice(1).toLowerCase()))
    .join("");

const COLORS: Record<string, string> = {
  messaging: "#0ea5e9",
  email: "#dc2626",
  productivity: "#7c3aed",
  google: "#16a34a",
  microsoft: "#2563eb",
  crm: "#ea580c",
  marketing: "#db2777",
  database: "#0f766e",
  vector: "#be185d",
  storage: "#0891b2",
  devops: "#475569",
  ecommerce: "#9333ea",
  finance: "#059669",
  ai: "#ec4899",
  iot: "#0f766e",
  social: "#1d4ed8",
  support: "#0d9488",
  hr: "#b45309",
  analytics: "#4f46e5",
  files: "#0891b2",
  misc: "#64748b",
  http: "#0ea5e9",
};

const OPERATIONS = ["create", "get", "getAll", "update", "delete", "search", "custom"];

function expandIntegration(spec: IntegrationSpec): NodeDef[] {
  const [name, icon, category, baseUrl, resources, hasTrigger] = spec;
  const base = slug(name);
  const credentialType = base;
  const color = COLORS[category] ?? "#64748b";
  const nodes: NodeDef[] = resources.map((res) => ({
    type: `${base}.${slug(res)}`,
    name: `${name}: ${res}`,
    category,
    icon,
    color,
    description: `عملیات روی ${res} در ${name}`,
    inputs: 1,
    outputs: ["main"],
    handler: "genericApi",
    credentialType,
    meta: { integration: name, resource: res, baseUrl },
    params: [
      P("operation", "عملیات", "select", {
        default: "getAll",
        options: OPERATIONS.map((o) => ({ value: o, label: o })),
      }),
      P("endpoint", "Endpoint (نسبی یا کامل)", "string", {
        placeholder: baseUrl ? `${baseUrl}/...` : "https://...",
        description: "آدرس API که فراخوانی می‌شود؛ می‌تواند عبارت داشته باشد",
      }),
      P("method", "متد", "select", { default: "GET", options: methodOptions }),
      P("body", "بدنه (JSON)", "json", { default: "{}" }),
      P("query", "Query (JSON)", "json", { default: "{}" }),
      P("simulate", "حالت شبیه‌سازی (بدون تماس واقعی)", "boolean", { default: false }),
    ],
  }));
  if (hasTrigger) {
    nodes.push({
      type: `${base}.trigger`,
      name: `${name} Trigger`,
      category: "trigger",
      icon,
      color,
      description: `شروع جریان با رویداد از ${name} (Webhook / Polling)`,
      inputs: 0,
      outputs: ["main"],
      trigger: true,
      handler: "trigger",
      credentialType,
      meta: { integration: name, baseUrl },
      params: [
        P("mode", "حالت", "select", {
          default: "webhook",
          options: [
            { value: "webhook", label: "Webhook" },
            { value: "polling", label: "Polling" },
          ],
        }),
        P("path", "مسیر Webhook", "string", { default: base }),
        P("event", "رویداد", "string", { default: "*" }),
        P("intervalMinutes", "بازه Polling (دقیقه)", "number", { default: 5 }),
      ],
    });
  }
  return nodes;
}

// ---------------------------------------------------------------------------
// خروجی نهایی کاتالوگ
// ---------------------------------------------------------------------------
export const NODE_CATALOG: NodeDef[] = [
  ...CORE_NODES,
  ...INTEGRATIONS.flatMap(expandIntegration),
];

export const NODE_MAP: Record<string, NodeDef> = Object.fromEntries(
  NODE_CATALOG.map((n) => [n.type, n]),
);

export const INTEGRATION_COUNT = INTEGRATIONS.length;
export const NODE_COUNT = NODE_CATALOG.length;

export function getNodeDef(type: string): NodeDef {
  return (
    NODE_MAP[type] ?? {
      type,
      name: type,
      category: "misc",
      icon: "❔",
      color: "#64748b",
      description: "نود ناشناخته",
      inputs: 1,
      outputs: ["main"],
      params: [],
      handler: "noop",
    }
  );
}

/** مقادیر پیش‌فرض پارامترهای یک نود */
export function defaultParams(type: string): Record<string, unknown> {
  const def = getNodeDef(type);
  const out: Record<string, unknown> = {};
  for (const p of def.params) if (p.default !== undefined) out[p.name] = p.default;
  return out;
}

/** انواع Credential قابل تعریف */
export const CREDENTIAL_TYPES: { type: string; label: string; fields: string[] }[] = [
  { type: "httpAuth", label: "HTTP Auth (Bearer / API Key / Basic)", fields: ["authType", "token", "headerName", "username", "password"] },
  { type: "llm", label: "LLM API Key (OpenAI / Anthropic / Gemini / ...)", fields: ["provider", "apiKey", "baseUrl"] },
  { type: "codex", label: "Codex (device-code)", fields: ["accessToken", "refreshToken", "accountId"] },
  { type: "telegram", label: "Telegram Bot", fields: ["botToken"] },
  { type: "bale", label: "Bale Bot", fields: ["botToken"] },
  { type: "soroush", label: "Soroush Bot", fields: ["botToken"] },
  { type: "slack", label: "Slack", fields: ["webhookUrl", "botToken"] },
  { type: "discord", label: "Discord Webhook", fields: ["webhookUrl"] },
  { type: "smtp", label: "SMTP", fields: ["host", "port", "user", "password", "from"] },
  { type: "imap", label: "IMAP", fields: ["host", "port", "user", "password"] },
  { type: "postgres", label: "PostgreSQL", fields: ["connectionString"] },
  { type: "mysql", label: "MySQL", fields: ["host", "port", "user", "password", "database"] },
  { type: "mongodb", label: "MongoDB", fields: ["connectionString"] },
  { type: "s3", label: "S3 / MinIO", fields: ["endpoint", "accessKey", "secretKey", "region"] },
  { type: "ftp", label: "FTP/SFTP", fields: ["host", "port", "user", "password"] },
  { type: "mqtt", label: "MQTT", fields: ["brokerUrl", "username", "password"] },
  { type: "vectorDb", label: "Vector DB", fields: ["provider", "url", "apiKey"] },
  { type: "oauth2", label: "OAuth2 Generic", fields: ["clientId", "clientSecret", "authUrl", "tokenUrl", "accessToken", "refreshToken"] },
  { type: "googleOAuth2", label: "Google OAuth2", fields: ["clientId", "clientSecret", "accessToken", "refreshToken"] },
  { type: "microsoftOAuth2", label: "Microsoft OAuth2", fields: ["clientId", "clientSecret", "tenantId", "accessToken", "refreshToken"] },
  { type: "vault", label: "HashiCorp Vault (External Secret Store)", fields: ["url", "token", "mountPath"] },
  { type: "generic", label: "Generic (API Key)", fields: ["apiKey", "baseUrl"] },
];
